### ISSUE TITLE
Cannot run pipelines on Linux

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#10]
The special option ```storage.components.path.prefix = file:/``` does not work on Linux now.

```
Reason:
 Can't load component: http://obeu.vse.cz:9080/resources/pipelines/created-1455211750950/components/4581eaa0-744f-4c1b-8855-00daf014349b 
Exception:
 com.linkedpipes.executor.module.boundary.ModuleFacade$ModuleException: Can't load bundle from given location!
	at com.linkedpipes.executor.module.boundary.impl.ModuleFacadeImpl.getComponent(ModuleFacadeImpl.java:208)
	at com.linkedpipes.executor.execution.contoller.PipelineExecutor.loadComponents(PipelineExecutor.java:409)
	at com.linkedpipes.executor.execution.contoller.PipelineExecutor.innerExecute(PipelineExecutor.java:303)
	at com.linkedpipes.executor.execution.contoller.PipelineExecutor.execute(PipelineExecutor.java:178)
	at com.linkedpipes.executor.execution.boundary.impl.ExecutorImpl.lambda$execute$16(ExecutorImpl.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.osgi.framework.BundleException: Unable to cache bundle: file://opt/etl/deploy/components/e-httpGetFile/e-httpGetFile-0.0.0.jar
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2969)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:140)
	at com.linkedpipes.executor.module.boundary.impl.ModuleFacadeImpl.getComponent(ModuleFacadeImpl.java:206)
	... 7 more
Caused by: java.net.UnknownHostException: opt
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:957)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:917)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1012)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:998)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:393)
	at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:525)
	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:166)
	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)
	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)
	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2965)
	... 10 more
 ```

**Comment by skodape** [comment]
There was bad example, fixed by  ea707268fb52564d769109a92e76310ee086afea.
