### ISSUE TITLE
Cannot run executor on Windows

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#11]
```
ERROR: Error reloading cached bundle, removing it: .\.felix\bundle1 (java.io.FileNotFoundException: .\.felix\bundle1\bundle.location (The system cannot find the file specified))
java.io.FileNotFoundException: .\.felix\bundle1\bundle.location (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.apache.felix.framework.util.SecureAction.getFileInputStream(SecureAction.java:453)
        at org.apache.felix.framework.cache.BundleArchive.readLocation(BundleArchive.java:1107)
        at org.apache.felix.framework.cache.BundleArchive.readBundleInfo(BundleArchive.java:973)
        at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:182)
        at org.apache.felix.framework.cache.BundleCache.getArchives(BundleCache.java:247)
        at org.apache.felix.framework.Felix.init(Felix.java:754)
        at org.apache.felix.framework.Felix.init(Felix.java:624)
        at org.apache.felix.framework.Felix.start(Felix.java:960)
        at com.linkedpipes.executor.module.boundary.impl.ModuleFacadeImpl.start(ModuleFacadeImpl.java:117)
        at com.linkedpipes.executor.module.boundary.impl.ModuleFacadeImpl.onApplicationEvent(ModuleFacadeImpl.java:167)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
        at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1271)
        at com.linkedpipes.executor.Executor.main(Executor.java:41)
```

**Comment by jakubklimek** [comment]
This was due to executor running twice.
