### ISSUE TITLE
API error : Entity too large

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#142]
I am trying to create a pipeline using the API. I run the following command 

```
curl -X POST -d @"Municipality of Athens Budget Revenue 2005.jsonld" http://localhost:8080/resources/
pipeline >> error.txt
```
and get the following error
```
Error: request entity too large<br> &nbsp; &nbsp;at readStream (C:\etl\deploy\frontend\node_modules\body-parser\node_modules\raw-body\index.js:196:17)<br>
 &nbsp; &nbsp;at getRawBody (C:\etl\deploy\frontend\node_modules\body-parser\node_modules\raw-body\index.js:106:12)<br>
 &nbsp; &nbsp;at read (C:\etl\deploy\frontend\node_modules\body-parser\lib\read.js:68:3)<br>
 &nbsp; &nbsp;at urlencodedParser (C:\etl\deploy\frontend\node_modules\body-parser\lib\types\urlencoded.js:109:5)<br>
 &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\etl\deploy\frontend\node_modules\express\lib\router\layer.js:95:5)<br>
 &nbsp; &nbsp;at trim_prefix (C:\etl\deploy\frontend\node_modules\express\lib\router\index.js:312:13)<br>
 &nbsp; &nbsp;at C:\etl\deploy\frontend\node_modules\express\lib\router\index.js:280:7<br>
 &nbsp; &nbsp;at Function.process_params (C:\etl\deploy\frontend\node_modules\express\lib\router\index.js:330:12)<br>
 &nbsp; &nbsp;at next (C:\etl\deploy\frontend\node_modules\express\lib\router\index.js:271:10)<br>
 &nbsp; &nbsp;at expressInit (C:\etl\deploy\frontend\node_modules\express\lib\middleware\init.js:33:5)
```

I have checked for server.js and the configuration for max_upload is 
```
gApp.use(gBodyParser.json({limit: '16mb'}));
```

The pipeline I am trying to upload is about 110KB in JSONLD format as downloaded from frontend.

**Comment by skarampatakis** [comment]
OK, I think I figured out how it works.
First
```
curl -X POST @ http://localhost:8080/resources/pipelines
```
to create the pipeline and get the id
and then 

```
curl -X PUT -d '@Municipality of Athens Budget Revenue 2015.jsonld' http://localhost:8080/resources/pipelines/3b490620-15ee-11e6-8301-8974f0f06fa0 --header 'Content-Type: application/json'
```

Pipeline is then created. However I cannot figure out how to start the pipeline execution. 
Maybe something with the URI data. Why not starting the execution with the id?

**Comment by skodape** [comment]
@skarampatakis The execution should be started by POST with the pipeline URI as a parameter pipeline, for example  
http://localhost:8080/resources/executions?pipeline=http://localhost:8080/resources/pipelines/created-1462793348608

**Comment by skarampatakis** [comment]
On the wiki is reffered that it should be run on 
```
/api/v1/execute?uri={IRI}
```
