### ISSUE TITLE
Files from local throws exception

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#146]
If you try to execute a pipeline with the Files from local DPU, the DPU throws this exception:

```
[Files from local] ERROR c.l.e.e.a.v.e.LocalizedException - LocalizedException: Component failed on throwable!
java.lang.NullPointerException: null
	at com.linkedpipes.plugin.extractor.local.FilesFromLocal.execute(FilesFromLocal.java:31) ~[na:na]
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:281) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:136) [executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
[Files from local] ERROR c.l.e.e.e.EventFactory - componentFailed
com.linkedpipes.etl.executor.api.v1.component.BaseComponent$ComponentFailed: Component failed on throwable!
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:302) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:136) ~[executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.lang.NullPointerException: null
	at com.linkedpipes.plugin.extractor.local.FilesFromLocal.execute(FilesFromLocal.java:31) ~[na:na]
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:281) ~[na:na]
	... 2 common frames omitted
```

Tested with the most recent develop version (bd2be3ec8a29c12228c3751c40b4026a426940a1).

**Comment by skodape** [comment]
Could you please check that the "Path to a local file or a directory" is set in the configuration dialog?

**Comment by jindrichmynarz** [comment]
Yes, that configuration is set.

**Comment by jindrichmynarz** [comment]
Works in 4fea9dfb1c6818ae8d08911b1ce2e275e4688df3.
