### ISSUE TITLE
l-filesToScp: session is down

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#160]
![image](https://cloud.githubusercontent.com/assets/718827/15577167/9a3d25f6-235b-11e6-8bda-00009ad91912.png)
```
2016-05-26 16:00:02,802 [Files to SCP] ERROR c.l.e.e.a.v.e.LocalizedException - LocalizedException: Can't create directory.
com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Session.openChannel(Session.java:853) ~[na:na]
	at com.linkedpipes.plugin.loader.scp.LoaderScp.secureCreateDirectory(LoaderScp.java:129) ~[na:na]
	at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:80) ~[na:na]
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:281) [api-dpu-v1-impl-0.0.0.jar:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:136) [executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2016-05-26 16:00:02,803 [Files to SCP] ERROR c.l.e.e.a.v.e.LocalizedException - LocalizedException: Component failed!
com.linkedpipes.etl.dpu.api.Component$ExecutionFailed: Can't create directory.
	at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:82) ~[na:na]
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:281) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:136) [executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Session.openChannel(Session.java:853) ~[na:na]
	at com.linkedpipes.plugin.loader.scp.LoaderScp.secureCreateDirectory(LoaderScp.java:129) ~[na:na]
	at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:80) ~[na:na]
	... 3 common frames omitted
2016-05-26 16:00:02,804 [Files to SCP] ERROR c.l.e.e.e.EventFactory - componentFailed
com.linkedpipes.etl.executor.api.v1.component.BaseComponent$ComponentFailed: Component failed!
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:300) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:136) ~[executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: com.linkedpipes.etl.dpu.api.Component$ExecutionFailed: Can't create directory.
	at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:82) ~[na:na]
	at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:281) ~[na:na]
	... 2 common frames omitted
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Session.openChannel(Session.java:853) ~[na:na]
	at com.linkedpipes.plugin.loader.scp.LoaderScp.secureCreateDirectory(LoaderScp.java:129) ~[na:na]
	at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:80) ~[na:na]
	... 3 common frames omitted
2016-05-26 16:00:02,804 [Files to SCP] ERROR c.l.e.e.e.EventFactory - executionFailed: Component execution failed.
```

**Comment by skodape** [comment]
Caused by invalid configuration, should be solved by #166.
