### ISSUE TITLE
t-sparqlConstruct

### ISSUE THREAD

**Issue by mlukasch** [linkedpipes/etl#163]
Hello,

with the master-branch executing a pipeline ends up in this problem:

`2016-05-27 13:22:00,678 [asynchExecutor-1] INFO  c.l.e.e.e.EventFactory - executionBegin
2016-05-27 13:22:00,679 [asynchExecutor-1] INFO  c.l.e.e.m.ModuleFacadeImpl - Loading jar file from: file:///srv/obeu/linkedpipes2/repos/etl/deploy/components/t-sparqlConstruct/t-sparqlConstruct-0.0.0.jar
2016-05-27 13:22:00,680 [asynchExecutor-1] ERROR c.l.e.e.e.EventFactory - initializationFailed: Initialization failed.
com.linkedpipes.etl.executor.pipeline.PipelineExecutor$InitializationFailure: com.linkedpipes.etl.executor.module.ModuleFacade$ModuleException: Can't start bundle!
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.initializeComponents(PipelineExecutor.java:276) ~[executor.jar:na]
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:143) ~[executor.jar:na]
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$8(ExecutionServlet.java:100) [executor.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
Caused by: com.linkedpipes.etl.executor.module.ModuleFacade$ModuleException: Can't start bundle!
	at com.linkedpipes.etl.executor.module.ModuleFacadeImpl.getComponent(ModuleFacadeImpl.java:221) ~[executor.jar:na]
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.initializeComponents(PipelineExecutor.java:273) ~[executor.jar:na]
	... 5 common frames omitted
Caused by: org.osgi.framework.BundleException: Unable to resolve com.linkedpipes.t-sparqlConstruct [1](R 1.0): missing requirement [com.linkedpipes.t-sparqlConstruct [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.linkedpipes.etl.dataunit.sesame.api.rdf)(version>=0.0.0)(!(version>=1.0.0))) Unresolved requirements: [[com.linkedpipes.t-sparqlConstruct [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.linkedpipes.etl.dataunit.sesame.api.rdf)(version>=0.0.0)(!(version>=1.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4114) ~[org.apache.felix.framework-5.0.1.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111) ~[org.apache.felix.framework-5.0.1.jar:na]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977) ~[org.apache.felix.framework-5.0.1.jar:na]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964) ~[org.apache.felix.framework-5.0.1.jar:na]
	at com.linkedpipes.etl.executor.module.ModuleFacadeImpl.getComponent(ModuleFacadeImpl.java:219) ~[executor.jar:na]
	... 6 common frames omitted
2016-05-27 13:22:00,680 [asynchExecutor-1] DEBUG o.o.s.n.NativeStore - Shutting down NativeStore...
2016-05-27 13:22:00,698 [asynchExecutor-1] DEBUG o.o.s.n.NativeStore - NativeStore shut down
2016-05-27 13:22:00,698 [asynchExecutor-1] DEBUG o.o.s.n.NativeStore - NativeStore shut down
2016-05-27 13:22:00,699 [asynchExecutor-1] INFO  c.l.e.e.e.EventFactory - executionFinished
2016-05-27 13:22:00,699 [asynchExecutor-1] DEBUG c.l.e.e.e.ExecutionModel - write (jsonld) ...
2016-05-27 13:22:00,704 [asynchExecutor-1] DEBUG c.l.e.e.e.ExecutionModel - write (jsonld) ... done`

**Comment by skodape** [comment]
@mlukasch Do other components work?

**Comment by mlukasch** [comment]
Hi @skodape No, sadly not...

`2016-05-27 13:32:09,699 [asynchExecutor-1] INFO  c.l.e.e.e.EventFactory - executionBegin
2016-05-27 13:32:09,700 [asynchExecutor-1] INFO  c.l.e.e.m.ModuleFacadeImpl - Loading jar file from: file:///srv/obeu/linkedpipes2/repos/etl/deploy/components/e-datasetMetadata/e-datasetMetadata-0.0.0.jar
2016-05-27 13:32:09,710 [asynchExecutor-1] ERROR c.l.e.e.e.EventFactory - initializationFailed: Initialization failed.
com.linkedpipes.etl.executor.pipeline.PipelineExecutor$InitializationFailure: com.linkedpipes.etl.executor.module.ModuleFacade$ModuleException: Can't start bundle!`

**Comment by mlukasch** [comment]
Sorry @skodape for wasting your time. I had used the configuration from a previous version. That was caused the issue...Thanks a lot and Sorry.
