### ISSUE TITLE
Clicking on execute in pipeline list logs exception in frontend and does not run

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#183]
```
[POST] /executions
  content-type:  undefined
Caught exception: [TypeError: Cannot call method 'push' of undefined] TypeError: Cannot call method 'push' of undefined
    at /opt/lp/etl/deploy/frontend/modules/unpacker.js:111:49
    at Request._callback (/opt/lp/etl/deploy/frontend/modules/unpacker.js:55:13)
    at Request.self.callback (/opt/lp/etl/deploy/frontend/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/opt/lp/etl/deploy/frontend/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/opt/lp/etl/deploy/frontend/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

**Comment by skodape** [comment]
Solved by d795de7b6bb339ed1138b485e4053c4a81155c31
