### ISSUE TITLE
Support for the "chips" component needed?

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#187]
I guess I need some special support for this UI component: https://github.com/linkedpipes/etl/blob/feature/dcatAp11/plugins/e-dcatAp11DatasetMetadata/src/main/resources/dialog.html#L71

Right now it ends during execution with:
```
com.linkedpipes.etl.executor.api.v1.RdfException: Component failed on Throwable.
	at com.linkedpipes.etl.executor.api.v1.RdfException.failure(RdfException.java:50) ~[api-executor-v1-0.0.0.jar:na]
	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:294) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:133) ~[executor.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: b0
	at org.openrdf.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:90) ~[sesame-model-4.0.0.jar:na]
	at org.openrdf.model.impl.SimpleIRI.<init>(SimpleIRI.java:79) ~[sesame-model-4.0.0.jar:na]
	at org.openrdf.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:98) ~[sesame-model-4.0.0.jar:na]
	at com.linkedpipes.plugin.extractor.dcatAp11DatasetMetadata.DcatAp11DatasetMetadata.addIRIs(DcatAp11DatasetMetadata.java:161) ~[na:na]
	at com.linkedpipes.plugin.extractor.dcatAp11DatasetMetadata.DcatAp11DatasetMetadata.execute(DcatAp11DatasetMetadata.java:71) ~[na:na]
	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:290) ~[na:na]
	... 2 common frames omitted
```

The configuration is saved as:
```
"http://etl.linkedpipes.com/resource/components/e-dcatAp11DatasetMetadata/languages": [
            {
              "IRI": "http://publications.europa.eu/resource/authority/language/CES",
              "value": "čeština",
              "$$hashKey": "object:3329"
            },
            {
              "IRI": "http://publications.europa.eu/resource/authority/language/ENG",
              "value": "english",
              "$$hashKey": "object:3330"
            }
```

**Comment by skodape** [comment]
Chips are designed to build list of strings or object. In your case it is list of objects (IRI, value). If you want to store the such list you need to manually convert it into the RDF objects and back.

There might be ways how to simplify this, however they can not be used with the your current implementation.
