### ISSUE TITLE
Error in Tabular: "not a valid absolute IRI"

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#199]
The Tabular component produces this error:

```
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI:
	at org.openrdf.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:90) ~[sesame-model-4.0.0.jar:na]
	at org.openrdf.model.impl.SimpleIRI.<init>(SimpleIRI.java:79) ~[sesame-model-4.0.0.jar:na]
	at org.openrdf.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:98) ~[sesame-model-4.0.0.jar:na]
	at com.linkedpipes.plugin.transformer.tabular.ColumnFactory.createColumnList(ColumnFactory.java:70) ~[na:na]
	at com.linkedpipes.plugin.transformer.tabular.Tabular.execute(Tabular.java:37) ~[na:na]
	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:290) ~[na:na]
	... 2 common frames omitted
```

It seems that Tabular is producing an empty string instead of a valid absolute IRI.

In order to replicate the error, you can use [this pipeline with sample data](https://github.com/linkedpipes/etl/files/343611/Sample.ESF-CZ.projects.jsonld.zip).

Tested using the latest develop version (447cd92a49734c31343d00f25fe15a2c4adef371).

**Comment by skodape** [comment]
Great you have included the test pipeline. 

There was a bug, where t-tabular use user given mapping even in full mapping mode - should be fixed now.

In you case the tabular has one user mapped column without type - the tabular then tries to create IRI of that empty type and failed. To address this I've also added a special error message for invalid types.

**Comment by jindrichmynarz** [comment]
Tested in d78bbe0f87041d0742cca7e3383b0dbb3222cd19, which works fine.
