### ISSUE TITLE
Excel to CSV conversion fails with a vague error

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#226]
Excel to CSV component can fail with a vague error, such as:

```
[Excel to CSV] ERROR c.l.e.e.e.EventFactory - componentFailed
com.linkedpipes.etl.executor.api.v1.RdfException: Component failed on Throwable.
       	at com.linkedpipes.etl.executor.api.v1.RdfException.failure(RdfException.java:50) ~[api-executor-v1-0.0.0.jar:na]
       	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:294) ~[na:na]
       	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:129) ~[executor.jar:na]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

The message `Component failed on Throwable.` doesn't help to diagnose the issue. It would be better to log the message of the Throwable or rethrow.

Tested using the latest develop version (01cb85e27fabf381a01c8ba1934d5982741638e5).

A pipeline to replicate the issue: [Test CSV conversion.jsonld.zip](https://github.com/linkedpipes/etl/files/442649/Test.CSV.conversion.jsonld.zip)

**Comment by jindrichmynarz** [comment]
Using fbfd8089180460358338d1a8facf57b661cd20c1 this exception turns out to be a `java.lang.OutOfMemoryError`.
