### ISSUE TITLE
DCAT-AP Dataset NPE: iriString must not be null

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#257]
In the latest develop (085e1ed802d4e23bae56c602f31c54c467f33c51) I encountered a null-pointer exception for the DCAT-AP Dataset component:

```
[DCAT-AP Dataset] ERROR c.l.e.e.e.EventFactory - componentFailed
com.linkedpipes.etl.executor.api.v1.RdfException: Component failed.
	at com.linkedpipes.etl.executor.api.v1.RdfException.failure(RdfException.java:34) ~[api-executor-v1-0.0.0.jar:na]
	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:290) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:121) ~[executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: iriString must not be null
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_111]
	at org.openrdf.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:87) ~[sesame-model-4.0.0.jar:na]
	at org.openrdf.model.impl.SimpleIRI.<init>(SimpleIRI.java:79) ~[sesame-model-4.0.0.jar:na]
	at org.openrdf.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:98) ~[sesame-model-4.0.0.jar:na]
	at com.linkedpipes.plugin.extractor.dcatAp11Dataset.DcatAp11Dataset.execute(DcatAp11Dataset.java:73) ~[na:na]
	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:286) ~[na:na]
	... 2 common frames omitted
```

The error appears even though the dataset IRI is set in the component's configuration.

**Comment by jindrichmynarz** [comment]
When I copied and pasted the DCAT AP Dataset's configuration into a new instance of this component, the error disappeared.
