### ISSUE TITLE
Error in the logs

### ISSUE THREAD

**Issue by mlukasch** [linkedpipes/etl#300]
Hello, probably the solution is just to delete the file:
Caused by: java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig

```13:49:39,831 INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'unpackerFacade': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.linkedpipes.etl.storage.pipeline.PipelineFacade com.linkedpipes.etl.storage.unpacker.UnpackerFacade.pipelines; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineFacade': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.linkedpipes.etl.storage.pipeline.PipelineManager com.linkedpipes.etl.storage.pipeline.PipelineFacade.pipelines; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineManager': Invocation of init method failed; nested exception is java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.linkedpipes.etl.storage.Storage.main(Storage.java:105)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.linkedpipes.etl.storage.pipeline.PipelineFacade com.linkedpipes.etl.storage.unpacker.UnpackerFacade.pipelines; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineFacade': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.linkedpipes.etl.storage.pipeline.PipelineManager com.linkedpipes.etl.storage.pipeline.PipelineFacade.pipelines; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineManager': Invocation of init method failed; nested exception is java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 13 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineFacade': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.linkedpipes.etl.storage.pipeline.PipelineManager com.linkedpipes.etl.storage.pipeline.PipelineFacade.pipelines; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineManager': Invocation of init method failed; nested exception is java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.linkedpipes.etl.storage.pipeline.PipelineManager com.linkedpipes.etl.storage.pipeline.PipelineFacade.pipelines; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineManager': Invocation of init method failed; nested exception is java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 26 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineManager': Invocation of init method failed; nested exception is java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 28 more
Caused by: java.lang.RuntimeException: Invalid pipeline: /data/lp/etl/storage/pipelines/created-1479895600445.trig
	at com.linkedpipes.etl.storage.pipeline.PipelineManager.initialize(PipelineManager.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 40 more
Caused by: org.openrdf.rio.RDFParseException: Expected a letter, found ' ' [line 342]
	at org.openrdf.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:359)
	at org.openrdf.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:635)
	at org.openrdf.rio.turtle.TurtleParser.reportError(TurtleParser.java:1394)
	at org.openrdf.rio.turtle.TurtleParser.parseQuotedLiteral(TurtleParser.java:691)
	at org.openrdf.rio.turtle.TurtleParser.parseValue(TurtleParser.java:651)
	at org.openrdf.rio.turtle.TurtleParser.parseObject(TurtleParser.java:527)
	at org.openrdf.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:458)
	at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:446)
	at org.openrdf.rio.trig.TriGParser.parseTriples(TriGParser.java:260)
	at org.openrdf.rio.trig.TriGParser.parseGraph(TriGParser.java:184)
	at org.openrdf.rio.trig.TriGParser.parseStatement(TriGParser.java:128)
	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:214)
	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:158)
	at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:270)
	at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:248)
	at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:235)
	at com.linkedpipes.etl.storage.pipeline.PipelineManager.loadPipeline(PipelineManager.java:98)
	at com.linkedpipes.etl.storage.pipeline.PipelineManager.initialize(PipelineManager.java:79)
	... 47 more
13:49:41,687 INFO  c.l.e.s.Configuration - Reading configuration file: configuration.properties
13:49:41,800 INFO  o.s.c.s.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@457e2f02: startup date [Tue Jan 24 13:49:41 CET 2017]; root of context hierarchy
13:49:41,829 INFO  o.s.b.f.x.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/context-storage.xml]
13:49:42,122 INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 
13:49:42,124 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'asynchExecutor' of type [class org.springframework.scheduling.config.TaskExecutorFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
13:49:42,124 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'asynchExecutor' of type [class org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

**Comment by skodapetr** [comment]
@mlukasch Reason for this error is corrupted pipeline. Is the pipeline public? Could you send us the pipeline file?

**Comment by mlukasch** [comment]
Deleted the file. I did a backup of the whole folder but it didnt complete. 
And I missed to check the backup first before deleting the pipeline file
So Im not sure which dataset it is exactly. It was (certainly) one of these: 
https://github.com/openbudgets/datasets/tree/master/OpenCoesione/pipelines
https://github.com/openbudgets/datasets/tree/master/Bonn/pipelines

**Comment by jakubklimek** [comment]
If this happens again, we can investigate further.
