### ISSUE TITLE
BundleException: Bundle symbolic name and version are not unique: org.apache.commons.codec:1.9.0

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#315]
When I run the executor from the develop version 8c0611026b53aa057905a0dd8aa7ad564fa7733e, it fails with the following error:

```
[main] ERROR c.l.e.e.m.ModuleFacade - Can't load bundle: /Users/mynarzjindrich/Dev/linkedpipes/etl/deploy/osgi/libs/commons-codec-1.9.jar
org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: org.apache.commons.codec:1.9.0
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1313)
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:113)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2998)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:140)
	at com.linkedpipes.etl.executor.module.ModuleFacade.lambda$start$0(ModuleFacade.java:231)
	at com.linkedpipes.etl.executor.module.ModuleFacade.scanDirectory(ModuleFacade.java:281)
	at com.linkedpipes.etl.executor.module.ModuleFacade.scanDirectory(ModuleFacade.java:283)
	at com.linkedpipes.etl.executor.module.ModuleFacade.start(ModuleFacade.java:228)
	at com.linkedpipes.etl.executor.module.ModuleFacade.onApplicationEvent(ModuleFacade.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1307)
	at com.linkedpipes.etl.executor.Executor.startExecutorService(Executor.java:37)
	at com.linkedpipes.etl.executor.Executor.main(Executor.java:41)
```

**Comment by jakubklimek** [comment]
Did you follow the update instructions in [readme](https://github.com/linkedpipes/etl/tree/develop)? I.e. deleting the deploy/osgi and deploy/jars folders?

**Comment by jindrichmynarz** [comment]
Ah, sorry. I read the update notes in the master version of the README.

Deleting the directories indeed fixes the error.

**Comment by satish14134** [comment]
where can we find these deploy,osgi and deploy/jars folders?

**Comment by jindrichmynarz** [comment]
That depends on what you have in `configuration.properties`:

- `executor.osgi.lib.directory` configures the location of the `osgi` folder.
- `storage.jars.directory` configures the location of the `jars` folder.

However, by default, when you compile LP-ETL, you'll find these folders at `deploy/osgi` and `deploy/jars` relative to the root folder.
