### ISSUE TITLE
FTP extractor cannot download data from data unit debug FTP

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#320]
```
2017-03-22 11:59:29,514 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - Host: etl.nkod.opendata.cz Path: /babccbda-f20b-4f4e-a1b3-a79b35250d02/078/data.ttl -> old.ttl
2017-03-22 11:59:29,574 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - Connect reply: 220, 220 Service ready for new user.

2017-03-22 11:59:29,575 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - sent: USER, USER anonymous
 -> 0
2017-03-22 11:59:29,576 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - received: null, 331 Guest login okay, send your complete e-mail address as password.
 -> 331
2017-03-22 11:59:29,576 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - sent: PASS, PASS 
 -> 0
2017-03-22 11:59:29,577 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - received: null, 230 User logged in, proceed.
 -> 230
2017-03-22 11:59:29,577 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - Connect reply: 230, 230 User logged in, proceed.

2017-03-22 11:59:29,577 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - sent: TYPE, TYPE I
 -> 0
2017-03-22 11:59:29,578 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - received: null, 200 Command TYPE okay.
 -> 200
2017-03-22 11:59:29,578 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - Downloading ...
2017-03-22 11:59:29,579 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - sent: PORT, PORT 195,113,18,51,205,113
 -> 0
2017-03-22 11:59:29,580 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - received: null, 501 PORT is disabled.
 -> 501
2017-03-22 11:59:29,590 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.binary.BinaryRDFWriterFactory
2017-03-22 11:59:29,590 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.jsonld.JSONLDWriterFactory
2017-03-22 11:59:29,590 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.n3.N3WriterFactory
2017-03-22 11:59:29,591 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.nquads.NQuadsWriterFactory
2017-03-22 11:59:29,591 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.ntriples.NTriplesWriterFactory
2017-03-22 11:59:29,593 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.rdfjson.RDFJSONWriterFactory
2017-03-22 11:59:29,593 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.rdfxml.RDFXMLWriterFactory
2017-03-22 11:59:29,593 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.trig.TriGWriterFactory
2017-03-22 11:59:29,593 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.trix.TriXWriterFactory
2017-03-22 11:59:29,593 [asynchExecutor-1] DEBUG o.e.r.r.RDFWriterRegistry - Registered service class org.eclipse.rdf4j.rio.turtle.TurtleWriterFactory
2017-03-22 11:59:29,600 [asynchExecutor-1] ERROR c.l.e.e.e.Execution - Component execution failed.
com.linkedpipes.etl.executor.ExecutorException: Component execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:46)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Failed to download file. See logs for more detail.
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:18)
	at com.linkedpipes.plugin.extractor.ftpfiles.FtpFiles.downloadFile(FtpFiles.java:145)
	at com.linkedpipes.plugin.extractor.ftpfiles.FtpFiles.execute(FtpFiles.java:61)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

**Comment by skodapetr** [comment]
There is message in log (now changed to ERROR level):
```
2017-03-22 11:59:29,580 [Extract from FTP] DEBUG c.l.p.e.ftpfiles.FtpFiles - received: null, 501 PORT is disabled.
 -> 501
```
The FTP extractor must be used in passive mode to extract from debug FTP server.
