### ISSUE TITLE
e-pipelineInput throws "Missing directory" error

### ISSUE THREAD

**Issue by marek-dudas** [linkedpipes/etl#340]
Even when I create a new pipeline with just pipelineInput and filesToLocal, the e-pipelineInput crashes with the following:

```
2017-04-08 08:42:27,722 [asynchExecutor-1] ERROR c.l.e.e.e.Execution - Component execution failed.
com.linkedpipes.etl.executor.ExecutorException: Component execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:46)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Missing directory.
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:18)
	at com.linkedpipes.plugin.extractor.pipelineInput.PipelineInput.execute(PipelineInput.java:42)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```
When I replace it with e.g. filesFromLocal, it works fine.

**Comment by skodapetr** [comment]
@marek-dudas Could you please retest?

**Comment by marek-dudas** [comment]
It works, thanks!
