### ISSUE TITLE
Excel to CSV throws NPE

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#358]
Excel to CSV component throws a NullPointerException when given <http://ec.europa.eu/eurostat/documents/345175/501971/EU-28_LAU_2016/9fa4f51f-6b97-4d80-b1a1-2a4cd3f7a0d1>. The executor logs this:

```
Caused by: java.lang.NullPointerException: null
	at com.linkedpipes.plugin.transformer.excel.to.csv.Parser.processSheet(Parser.java:106)
	at com.linkedpipes.plugin.transformer.excel.to.csv.Parser.processEntry(Parser.java:70)
	at com.linkedpipes.plugin.transformer.excel.to.csv.ExcelToCsv.execute(ExcelToCsv.java:39)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

A pipeline to reproduce the issue is [here](https://github.com/linkedpipes/etl/files/947043/Local.Administrative.Units.LAU.2016.jsonld.zip).

Tested using the develop version 9a42adc02da86a8cdc00bfa6fdd45ac09f568a05.

**Comment by jindrichmynarz** [comment]
Fixed in 9050cd725dc037e80aacf50275ac817a843cf82c.
