### ISSUE TITLE
Can't get it working on MacOS

### ISSUE THREAD

**Issue by patzomir** [linkedpipes/etl#371]
I can't get the ETL working on MacOS.
When I try to execute a pipeline, I get this error stack:
```
2017-04-27 14:47:19,217 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - Initializing NativeStore...
2017-04-27 14:47:24,221 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - Data dir is /Users/plamentarkalanov/Documents/Ontotext/LinkedPipes/executor/data/9be7c40c-e1c3-4477-8aad-9a440142f786/working/pipeline_repository-1
2017-04-27 14:47:24,225 [asynchExecutor-1] DEBUG o.e.r.s.n.TripleStore - No indexes specified, using default indexes: spoc,posc
2017-04-27 14:47:24,226 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - NativeStore initialized
2017-04-27 14:47:24,336 [asynchExecutor-1] ERROR c.l.e.e.e.Execution - Can't load dataunits.
com.linkedpipes.etl.executor.ExecutorException: Can't instantiate data unit: http://localhost:8080/resources/pipelines/created-1493292440008/blank/24
	at com.linkedpipes.etl.executor.dataunit.DataUnitManager.createDataUnitContainer(DataUnitManager.java:158)
	at com.linkedpipes.etl.executor.dataunit.DataUnitManager.initialize(DataUnitManager.java:59)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.initializeDataUnits(PipelineExecutor.java:200)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.initialize(PipelineExecutor.java:138)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:79)
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.linkedpipes.etl.executor.module.ModuleException: No factory can instantiate required data unit.
	at com.linkedpipes.etl.executor.module.ModuleFacade.getDataUnit(ModuleFacade.java:171)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.lambda$initializeDataUnits$0(PipelineExecutor.java:198)
	at com.linkedpipes.etl.executor.dataunit.DataUnitManager.createDataUnitContainer(DataUnitManager.java:156)
	... 8 common frames omitted
2017-04-27 14:47:24,361 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - Shutting down NativeStore...
2017-04-27 14:47:24,362 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - NativeStore shut down
2017-04-27 14:47:24,363 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - NativeStore shut down
```

**Comment by jindrichmynarz** [comment]
Can you share the pipeline too? I'm using LP-ETL on OS X with no problems.

**Comment by patzomir** [comment]
Even using a simple one component pipeline raises this error. E.g.:
```json
{
  "@graph": [
    {
      "@graph": [
        {
          "@id": "http://localhost:8080/resources/pipelines/created-1493319479356",
          "@type": [
            "http://linkedpipes.com/ontology/Pipeline"
          ],
          "http://etl.linkedpipes.com/ontology/version": [
            {
              "@type": "http://www.w3.org/2001/XMLSchema#int",
              "@value": "1"
            }
          ],
          "http://www.w3.org/2004/02/skos/core#prefLabel": [
            {
              "@value": "http://localhost:8080/resources/pipelines/created-1493319479356"
            }
          ]
        },
        {
          "@id": "http://localhost:8080/resources/pipelines/created-1493319479356/components/c59a7789-7049-4b02-ab61-fa2607bb449b",
          "@type": [
            "http://linkedpipes.com/ontology/Component"
          ],
          "http://linkedpipes.com/ontology/configurationGraph": [
            {
              "@id": "http://localhost:8080/resources/pipelines/created-1493319479356/components/c59a7789-7049-4b02-ab61-fa2607bb449b/configuration"
            }
          ],
          "http://linkedpipes.com/ontology/template": [
            {
              "@id": "http://etl.linkedpipes.com/resources/components/e-filesFromLocal/0.0.0"
            }
          ],
          "http://linkedpipes.com/ontology/x": [
            {
              "@type": "http://www.w3.org/2001/XMLSchema#integer",
              "@value": "400"
            }
          ],
          "http://linkedpipes.com/ontology/y": [
            {
              "@type": "http://www.w3.org/2001/XMLSchema#integer",
              "@value": "40"
            }
          ],
          "http://www.w3.org/2004/02/skos/core#prefLabel": [
            {
              "@value": "Files from local"
            }
          ]
        }
      ],
      "@id": "http://localhost:8080/resources/pipelines/created-1493319479356"
    },
    {
      "@graph": [
        {
          "@id": "http://etl.linkedpipes.com/resources/components/e-filesFromLocal/0.0.0/new/1",
          "@type": [
            "http://plugins.linkedpipes.com/ontology/e-filesFromLocal#Configuration"
          ],
          "http://plugins.linkedpipes.com/ontology/e-filesFromLocal#path": [
            {
              "@value": ""
            }
          ],
          "http://plugins.linkedpipes.com/ontology/e-filesFromLocal#pathControl": [
            {
              "@id": "http://plugins.linkedpipes.com/resource/configuration/None"
            }
          ],
          "http://plugins.linkedpipes.com/ontology/e-filesFromLocal#pathontrol": [
            {
              "@id": "http://plugins.linkedpipes.com/resource/configuration/None"
            }
          ]
        }
      ],
      "@id": "http://localhost:8080/resources/pipelines/created-1493319479356/components/c59a7789-7049-4b02-ab61-fa2607bb449b/configuration"
    }
  ]
}
```

**Comment by skodapetr** [comment]
Could you please check that the configuration property executor.osgi.lib.directory points to a directory with directories core and libs? And that the core directory contains files: dataunit-core-0.0.0.jar and rdf-utils-rdf4j-0.0.0.jar ?

**Comment by patzomir** [comment]
Ugh, I had forgotten to alter the executor.banned_jar_iri_patterns. Sorry!
