### ISSUE TITLE
DCAT-AP Dataset produces empty language tags

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#383]
The DCAT-AP Dataset component produces empty language tags if they are omitted from its configuration. For example, it output `"statistics"@` instead of `"statistics"`. This results in syntactically invalid RDF, which makes the pipeline invalid, so that is cannot be opened.

Side note: fortunately, the pipeline file can be edited directly, so that the pipeline is not lost and can be re-opened after the syntax errors are fixed.

This can be resolved in several ways, for example:

* When no language tag is provided, a plain literal without a language tag is stored (e.g., `"statistics"` instead of `"statistics"@`).
* When no language tag is provided, a warning is shown telling the user that the component's configuration is invalid. This requires validation of the configuration. I'm not sure if any validation is done, but it may be a good use case for [SHACL](https://www.w3.org/TR/shacl).

Tested using the latest develop version 1119fce83501aeee0ca73c466d89aa09ac042433.

**Comment by jindrichmynarz** [comment]
Throws NPE in f73314dc3ef7f8ce67a99bda1a88a2eb4c84d98f:

```
Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.eclipse.rdf4j.model.impl.SimpleLiteral.setLanguage(SimpleLiteral.java:121)
	at org.eclipse.rdf4j.model.impl.SimpleLiteral.<init>(SimpleLiteral.java:85)
	at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createLiteral(AbstractValueFactory.java:108)
	at com.linkedpipes.plugin.extractor.dcatAp11Dataset.DcatAp11Dataset.addLocalizedString(DcatAp11Dataset.java:199)
	at com.linkedpipes.plugin.extractor.dcatAp11Dataset.DcatAp11Dataset.execute(DcatAp11Dataset.java:59)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

**Comment by skodapetr** [comment]
@jakubklimek Should we support strings without a language?

**Comment by jakubklimek** [comment]
We should definitely not break a pipeline when the language tag is missing. That I think is the point here. We do not do configuration validation yet.
We should not generate strings without language tags where DCAT-AP expects langString. 

The component should therefore fail when the language tag is not provided in configuration.

**Comment by jindrichmynarz** [comment]
Empty language labels are supported in 0b04af2c96e497f1c8a9518eaaeba0dddb62086e.
