### ISSUE TITLE
NullPointerException in executor-monitor.sh

### ISSUE THREAD

**Issue by jmvanel** [linkedpipes/etl#385]
This happens with the source from git. 

```shell
uname -a
Linux jmv-SMBIOSation 4.8.0-51-generic #54-Ubuntu SMP Tue Apr 25 16:32:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

```
jmv@jmv-SMBIOSation:~/src/etl/deploy$ ./executor.sh >> executor.log &
[1] 27302
jmv@jmv-SMBIOSation:~/src/etl/deploy$ ./executor-monitor.sh >> executor-monitor.log &
[2] 27332
jmv@jmv-SMBIOSation:~/src/etl/deploy$ Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'virtualFileSystem': Unsatisfied dependency expressed through field 'executions'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionFacade': Unsatisfied dependency expressed through field 'storage'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionStorage': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.linkedpipes.etl.executor.monitor.ExecutorMonitor.main(ExecutorMonitor.java:104)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionFacade': Unsatisfied dependency expressed through field 'storage'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionStorage': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
	... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionStorage': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
	... 28 more
Caused by: java.lang.NullPointerException
	at com.linkedpipes.etl.executor.monitor.execution.ExecutionStorage.onInit(ExecutionStorage.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 40 more
```

**Comment by skodapetr** [comment]
@jmvanel Hi, could you please check that the working directory exists (and it's not a file). If it does not exists then whether the LP process have right to create it.

**Comment by jmvanel** [comment]
@skodapetr , I'm not sure what you mean by "the working directory" .

For me , it is /home/jmv/src/etl/deploy , that was created by Maven.

I set these keys in configuration.properties : 
```properties
grep jmv configuration.properties 
executor.log.directory = /home/jmv/db/log
executor.osgi.lib.directory = /home/jmv/db/osgi
executor-monitor.log.directory = /home/jmv/db/log
storage.jars.directory = /home/jmv/db/jars
storage.directory = /home/jmv/db/storage
storage.log.directory = /home/jmv/db/log
```

SUGGESTIONS
- write a configuration.properties.sample file that is ready to run without any editions
- and/or complete this sentence in README.md "Now edit the configuration file, mainly adding paths to working, storage, log and library directories. Especially:"

**Comment by skodapetr** [comment]
@jmvanel Thanks for the suggestions. 
It seems that the property ```executor.execution.working_directory``` is missing in your list. 
Also if you do not plan to copy anything from ```/home/jmv/src/etl/deploy``` directory into the ```/home/jmv/db``` then I would suggest to add:
```properties
executor.execution.working_directory = /home/jmv/db/executions
```
and update
```properties
executor.osgi.lib.directory = /home/jmv/src/etl/deploy/osgi
storage.jars.directory = /home/jmv/src/etl/deploy/jars
```
Properties ```executor.osgi.lib.directory``` and ```storage.jars.directory``` require files from the deploy directory (plugins, libraries).

**Comment by jmvanel** [comment]
Thank for filling the README ( duplicate  ```storage.log.directory``` ) ,
but that does not solve the issue .

Have you tried  running from sources on an empty machine like I did ?
I suspect an OSGI dependency problem.

**Comment by jmvanel** [comment]
IT WORKS !

Just set the missing key executor.execution.working_directory .
