### ISSUE TITLE
Invalid executions not deleted

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#393]
Executions of corrupted pipelines (caused by #375) are not deleted. Invalid pipelines are kept in `working/data/{execution}/definition/definition.jsonld`. Instead of JSON-LD, they contain errors in HTML:

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/v1/pipelines/unpack. Reason:
<pre>    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: Cycle detected.</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a><hr/>
</body>
</html>
```

This causes the storage to log errors trying to parse these HTML files as JSON-LD during its start up:

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.BufferedReader@21db454c; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
	at com.github.jsonldjava.utils.JsonUtils.fromReader(JsonUtils.java:116)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:97)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:77)
	at org.eclipse.rdf4j.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:68)
	... 36 common frames omitted
```

In spite of these errors LP-ETL continues to operate normally. Probably the key question here is thus why LP-ETL saves the HTML errors in place of the JSON-LD files.

**Comment by jindrichmynarz** [comment]
This is quite problematic, since an invalid execution causes LP-ETL to refuse further executions. Unfortunately, the error message does not contain information which execution is invalid, so it needs to be found manually, e.g., by running this in the working directory:

```sh
find . -type f -name definition.jsonld -exec echo {} \; -exec riot --validate {} \;
```

**Comment by skodapetr** [comment]
It should not cause that, are you sure there is not another problem?

**Comment by jindrichmynarz** [comment]
I think your question relates to #435 instead of this one, correct?

**Comment by skodapetr** [comment]
Yes, the "invalid" executions are "garbage" and they produce error log during loading of executor-monitor but otherwise they should have no effect.

**Comment by jindrichmynarz** [comment]
OK, I think I can narrow the problem down. If an invalid execution of a pipeline occurs (e.g., the executor is killed during its runtime), no other valid executions of the same pipeline can be resumed even if the invalid execution is deleted.

**Comment by skodapetr** [comment]
The original issue was about not handling properly the error in pipeline unpacking done by storage. This should be handled by now and will be improved a little bit more in the future.

The described error with one invalid pipeline blocking other is a different issue and as of now I can not think of a reason why that could have happend.  Should that happen again we will create a new issue.
