### ISSUE TITLE
Tabular: undescribed NPE

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#396]
In [this pipeline](https://github.com/linkedpipes/etl/files/1045157/Tabular.NPE.jsonld.zip) Tabular throws an undescribed `NullPointerException`:

```
Caused by: java.lang.NullPointerException: null
	at com.linkedpipes.plugin.transformer.tabular.Parser.parse(Parser.java:91)
	at com.linkedpipes.plugin.transformer.tabular.Tabular.execute(Tabular.java:58)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

Tested using the latest develop version 344846a472fe14e5456e9443278e9cb7862abf1e.

**Comment by jindrichmynarz** [comment]
Narrowing this issue down, it happens (at least) when the input CSV file is empty. In that case, Tabular should throw a descriptive exception containing the name of the empty file.

**Comment by jindrichmynarz** [comment]
Empty file or file with only whitespace is valid CSV according to the [CSV Lint](https://csvlint.io), so Tabular should be able to handle them. A natural output for such inputs would be empty RDF.

**Comment by jindrichmynarz** [comment]
When provided with empty input, Tabular in the version 09d81d1f6f7ebbf8698c54ace9c31a3f985a999b produces empty output. This fixes the issue.
