### ISSUE TITLE
XSLT transformer: configuration data unit required?

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#398]
Does XSLT transformer now require configuration to be passed as a data unit? Without a configuration input, just using the configuration via the component's dialog, an error is thrown:

```
com.linkedpipes.etl.executor.ExecutorException: Can't bindToPipeline component.
	at com.linkedpipes.etl.executor.component.ExecuteComponent.initialize(ExecuteComponent.java:106)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.execute(ExecuteComponent.java:71)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponent(PipelineExecutor.java:253)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponents(PipelineExecutor.java:230)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:81)
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Missing data unit: Configuration
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.bindPort(SequentialWrap.java:153)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.bingPorts(SequentialWrap.java:126)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.initialize(SequentialWrap.java:54)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.initialize(ExecuteComponent.java:104)
	... 8 common frames omitted
```

Minimal pipeline to replicate the issue is [here](https://github.com/linkedpipes/etl/files/1045555/XSLT.transformer-.missing.configuration.jsonld.zip).

Tested using the latest develop version 344846a472fe14e5456e9443278e9cb7862abf1e.

**Comment by jindrichmynarz** [comment]
Fixed in fd194f2aa4f49eb44e79b45d2b9e2057e3745c14.
