### ISSUE TITLE
Enhancement: support blank nodes in configuration

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#400]
Blank nodes are not supported in configuration for LP-ETL components. This is already documented. However, if there is not a strong reason not to support them, it would be convenient for users if they were supported. First, users could use full syntax of RDF without worrying about LP-ETL-specific restrictions. Second, in some cases blank nodes are easier to generate than unique IRIs (in the absence of unique keys, unique IRIs would require to use `uuid()`).

If blank nodes will not be supported, then can we get a more precise error? Currently, if blank nodes are used in configuration, the exception `Not a valid (absolute) IRI` is thrown:

```
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: node1bhjqgl77x119679
	at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:76)
	at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:65)
	at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:88)
	at com.linkedpipes.etl.rdf.utils.rdf4j.BufferedTripleWriter.typed(BufferedTripleWriter.java:37)
	at com.linkedpipes.etl.dataunit.core.rdf.DefaultSingleGraphDataUnit.writeStatement(DefaultSingleGraphDataUnit.java:130)
	at com.linkedpipes.etl.dataunit.core.rdf.DefaultSingleGraphDataUnit.lambda$write$0(DefaultSingleGraphDataUnit.java:83)
	at com.linkedpipes.etl.dataunit.core.rdf.ActionExecutor.execute(ActionExecutor.java:18)
	... 13 common frames omitted
```

While it is true that blank nodes are not valid (absolute) IRIs, the error could be more specific. Upon seeing this error, the users may suspect they have syntax errors in the IRIs. The error can report explicitly that blank nodes are unsupported.

**Comment by jakubklimek** [comment]
The support is not planned as it is always possible to use uuid() - I do it this way - and blank nodes only cause trouble.

However, the error could be more desriptive.

**Comment by jindrichmynarz** [comment]
So perhaps the component can simply raise an error that the configuration contains blank nodes if the following query evaluates to `true`:

```sparql
ASK {
  ?s ?p ?o .
  FILTER (isBlank(?s) || isBlank(?o))
}
```
