### ISSUE TITLE
Tabular: empty trailing line causes an error

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#403]
If you provide Tabular with a CSV that has an empty line at the end, it causes an error:

```
Caused by: org.supercsv.exception.SuperCsvException: unexpected end of file while reading quoted column beginning on line 372 and ending on line 373
	at org.supercsv.io.Tokenizer.readColumns(Tokenizer.java:146)
	at org.supercsv.io.AbstractCsvReader.readRow(AbstractCsvReader.java:179)
	at org.supercsv.io.CsvListReader.read(CsvListReader.java:69)
	at com.linkedpipes.plugin.transformer.tabular.Parser.parse(Parser.java:122)
	at com.linkedpipes.plugin.transformer.tabular.Tabular.execute(Tabular.java:58)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

A test pipeline cannot be provided easily, since the Text Holder trims any trailing whitespace from its input. However, any CSV with trailing line loaded from the file system will do.

I think that Tabular should ignore any empty lines.

Tested using the develop version 09d81d1f6f7ebbf8698c54ace9c31a3f985a999b.

**Comment by skodapetr** [comment]
@jindrichmynarz You can upload file and use HTTP get? From the exception it looks like there problem with (unclosed) quote.

**Comment by jindrichmynarz** [comment]
Yes, you're right. I though the issue is with the empty trailing line, but it is in fact caused by an unescaped quote (`"""` should be represented as `""""`) earlier in the CSV. When I fix the escaping, the empty trailing line is ignored.
