### ISSUE TITLE
HTTP GET list: skips remaining files when it can't read status code

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#405]
I have a pipeline that downloads 314 files via HTTP GET list. Not all files are downloaded. When the component logs "Can't read status code", the remaining files are skipped. As in the execution logs:

```
2017-06-12 14:21:18,386 [pool-3-thread-1] DEBUG c.l.p.e.h.UriDownloader - Downloading 76/314 : http://apl.czso.cz/iSMS/cisexp.jsp?kodcis=52&typdat=1&cisvaz=47_50&cisjaz=203&format=0
2017-06-12 14:29:59,182 [pool-3-thread-1] WARN  c.l.p.e.h.UriDownloader - Can't read status code.
2017-06-12 14:29:59,192 [HTTP get list] INFO  c.l.p.e.h.HttpGetFiles - Downloaded 1/314
```

What follows these logs is from the subsequent components in the pipeline. Only 75 files prior to the "Can't read status code" are downloaded. It seems as if the components skips not only the file that caused the error, but also any following files. Also, for some reason, after the error the component logs that it downloaded 1/314 files.

As for configuration of the component, *Skip on error* is enabled and *Number of threads used for download* is set to the default value 1.

Tested using the develop version e075246dce28cfab21b0535b7d0691515b659339.

**Comment by jindrichmynarz** [comment]
Is this expected to appear in logs when an HTTP request fails?

```
2017-06-19 09:47:40,759 [pool-4-thread-1] ERROR c.l.p.e.h.UriDownloader - Can't read response code for file: /Users/mynarzjindrich/Dev/linkedpipes/etl-deploy/lp/etl/working/data/24c0ec18-8bce-47af-8887-9b53610891a6/working/temp-27/f7ea6f67efe2573793b89bca3b8cd09d7a4a9b79.xml
java.net.SocketException: Connection reset
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.linkedpipes.plugin.extractor.httpgetfiles.UriDownloader$Worker.call(UriDownloader.java:85)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.linkedpipes.plugin.extractor.httpgetfiles.UriDownloader.logDetails(UriDownloader.java:241)
	at com.linkedpipes.plugin.extractor.httpgetfiles.UriDownloader.access$800(UriDownloader.java:19)
	at com.linkedpipes.plugin.extractor.httpgetfiles.UriDownloader$Worker.call(UriDownloader.java:82)
	... 4 common frames omitted
```

**Comment by skodapetr** [comment]
Well, there is space for an improvement (remove the duplicity, improve thread name ... ) however I think it does deliver the general idea.

**Comment by jindrichmynarz** [comment]
Only the requests that end up in error are skipped in 63c95bec2c1c6106174344306772939e7d8a6041.
