### ISSUE TITLE
Chunked RDF to file: NullPointerException

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#411]
Chunked RDF to file fails with `NullPointerException`. Here's a [pipeline to reproduce the issue](https://github.com/linkedpipes/etl/files/1073792/LAU.v3-.test.Chunked.RDF.to.file.simple.jsonld.zip).

```
com.linkedpipes.etl.executor.ExecutorException: Component execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:46)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.writePrefixes(RdfToFileChunked.java:126)
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.export(RdfToFileChunked.java:76)
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.execute(RdfToFileChunked.java:52)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

Tested using the develop version e075246dce28cfab21b0535b7d0691515b659339.

**Comment by jindrichmynarz** [comment]
Still a NPE in ea55b8f69c5cd5464927f735ad56cc21fa5d6cff:

```
2017-06-19 20:15:12,699 [Chunked RDF to file] INFO  c.l.e.e.e.Execution - Component code failed : http://localhost:8080/resources/pipelines/created-1497424155015/15
com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:46)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.writePrefixes(RdfToFileChunked.java:126)
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.export(RdfToFileChunked.java:76)
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.execute(RdfToFileChunked.java:52)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
2017-06-19 20:15:12,707 [asynchExecutor-1] ERROR c.l.e.e.e.Execution - Component execution failed : http://localhost:8080/resources/pipelines/created-1497424155015/15
com.linkedpipes.etl.executor.ExecutorException: Component execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:46)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.writePrefixes(RdfToFileChunked.java:126)
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.export(RdfToFileChunked.java:76)
	at com.linkedpipes.plugin.transformer.rdftofile.RdfToFileChunked.execute(RdfToFileChunked.java:52)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

**Comment by skodapetr** [comment]
@jindrichmynarz Could you please re-test?

**Comment by jindrichmynarz** [comment]
Retested: works in 8e528b20778aba6e9722187403d785b6d20b6c28.
