### ISSUE TITLE
HTTP GET list: HTTPS is not supported

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#426]
When HTTP GET list is asked to download a HTTPS URL, it throws an error:

```
javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.linkedpipes.plugin.extractor.httpgetfiles.UriDownloader$Worker.downloadFile(UriDownloader.java:107)
	at com.linkedpipes.plugin.extractor.httpgetfiles.UriDownloader$Worker.call(UriDownloader.java:76)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Is the component only intended for HTTP URLs, as its name may suggest? Or is this a bug?

A pipeline to reproduce the issue is [here](https://github.com/linkedpipes/etl/files/1124704/Test.HTTP.GET.list-.HTTPS.jsonld.zip).

Tested using the develop version e6850ae954b511710e9699b7d7741657a5a80444.

**Comment by skodapetr** [comment]
This seems to be a problem of java:
```
From jdk 8u66, using a custom HostnameVerifier does not send Extended server_name extension during handshake. This bug will be fixed in version 8u152.
```
https://stackoverflow.com/questions/41692736/all-trusting-hostnameverifier-causes-ssl-errors-with-httpurlconnection

**Comment by jindrichmynarz** [comment]
A similar exception occurs in HTTP GET component:

```
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't copy file.
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:18)
	at com.linkedpipes.plugin.extractor.httpget.HttpGet.execute(HttpGet.java:103)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.linkedpipes.plugin.extractor.httpget.HttpGet.execute(HttpGet.java:100)
	... 3 common frames omitted
```

However, HTTPS URLs from GitHub, such as <https://raw.githubusercontent.com/openbudgets/data-model/master/code_lists.ttl>, work. What's the difference?

**Comment by skodapetr** [comment]
Yes, the exception is same as it is probably a bug in Java. We can try workaround.
If this only happen with ```http://httpbin.org/delay/10``  we may wait for fix in the Java, or are there other URL with this problem?

**Comment by jindrichmynarz** [comment]
I haven't tried any other HTTPS URLs. Given that `httpbin` is also available via HTTP and it is used only for testing I think don't need the work-around and instead have this fixed once the version of Java that LP-ETL uses is upgraded.

You can either leave this issue open as a reminder or close it.

**Comment by jakubklimek** [comment]
This is fixed by supporting only newer Java versions.
