### ISSUE TITLE
SPARQL CONSTRUCT to file list: iriString must not be null

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#427]
SPARQL CONSTRUCT to file list throws `iriString must not be null` exception.

```
Caused by: java.lang.NullPointerException: iriString must not be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:73)
	at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:65)
	at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:88)
	at com.linkedpipes.plugin.transformer.sparql.constructtofilelist.SparqlConstructToFileList.executeTask(SparqlConstructToFileList.java:111)
	at com.linkedpipes.plugin.transformer.sparql.constructtofilelist.SparqlConstructToFileList.executeTasks(SparqlConstructToFileList.java:100)
	at com.linkedpipes.plugin.transformer.sparql.constructtofilelist.SparqlConstructToFileList.executeTaskGroups(SparqlConstructToFileList.java:77)
	at com.linkedpipes.plugin.transformer.sparql.constructtofilelist.SparqlConstructToFileList.execute(SparqlConstructToFileList.java:57)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	... 2 common frames omitted
```

The exception also appeared in #257, but it seems unrelated.

I used [this configuration](https://github.com/linkedpipes/etl/files/1134797/config.ttl.gz) on [this dataset](https://github.com/linkedpipes/etl/files/1134798/data.ttl.gz).

Tested using the develop version 1b6ef835dd2bff425b9caa77860c13bf61fd199f.

**Comment by skodapetr** [comment]
The sctfl:graph should be sctfl:outputGraph .

**Comment by jindrichmynarz** [comment]
You're right. This is an error in the configuration. 

The [demo pipeline](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1490806501982) also uses `sctfl:graph`, so it should be updated.
