### ISSUE TITLE
Blank node generated for rdfRepositoryType prevents pipeline execution

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#450]
I have a [pipeline](https://github.com/linkedpipes/etl/files/1169258/geocoding_with_nominatim.jsonld.zip) that fails to execute. When its execution is triggered, this error is raised:

```
Caused by: org.eclipse.rdf4j.rio.RDFParseException: Could not parse JSONLD
	at org.eclipse.rdf4j.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:74)
	at com.linkedpipes.etl.executor.monitor.execution.PipelineLoader.loadStream(PipelineLoader.java:200)
	... 38 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.BufferedReader@77ea33c6; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
	at com.github.jsonldjava.utils.JsonUtils.fromReader(JsonUtils.java:116)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:97)
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:77)
	at org.eclipse.rdf4j.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:68)
	... 39 common frames omitted
```

The pipeline `definition.jsonld` generated for the execution contains an HTML error instead of JSON-LD:

```html
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/v1/pipelines/unpack. Reason:
<pre>    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java. lang.IllegalArgumentException: Not a valid (absolute) IRI: genid-edbfb36dd2ce4f82b4bd303f003c0f7e-b0</pre></p>
```

The pipeline itself contains a blank node generated for the property `rdfRepositoryType`:

```json
"http://linkedpipes.com/ontology/rdfRepositoryType": [{
  "@id": "_:genid-66c5dfac319740e282ff76cb3d81368c-b0"
}]
```

Why is a blank node generated for this property when LP-ETL does not support blank nodes?

Tested using the develop version 4b58403d29bb9b631eb9329d2a1eeca3d5ae8d2f.

**Comment by skodapetr** [comment]
@jindrichmynarz How do you created the pipeline, is it a copy of another one? Have you used the pipeline detail dialog?

**Comment by jindrichmynarz** [comment]
This is a pipeline that I have created before the execution profile option was introduced.

**Comment by skodapetr** [comment]
@jindrichmynarz So you open the pipeline in pipeline edit, hit execute. Can you check whether the blank node is in the pipeline definition (ie. in the jsonld, that can be accessed under the pipeline IRI).

**Comment by jindrichmynarz** [comment]
Yes, the blank node is in the pipeline definition, as shown in the issue above.

**Comment by skodapetr** [comment]
This should prevent future blank nodes, it does not fix broken pipelines. Pipeline can be fixed by opening the pipeline detail dialog and setting value to repository type (NativeStore).

**Comment by jindrichmynarz** [comment]
How should I test this?

**Comment by skodapetr** [comment]
Well from what I know (and how I test this) it happened when you opened the pipeline edit dialog, close the dialog (ie. left the repository type unchanged) and save the pipeline.

**Comment by jindrichmynarz** [comment]
I manually removed `rdfRepositoryType` blank node, imported the pipeline, opened its pipeline detail dialog, closed it, and successfully executed the pipeline using the develop version 622aca9c523d66f65d381b4fa4e3f08b7f0d9a90.
