### ISSUE TITLE
SparqlSelectMultiple renamed to SparqlSelectMulti in runtime configuration

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#490]
I get
```
Cause: 
Can't get configuration object of type http://plugins.linkedpipes.com/ontology/t-sparqlSelectMulti#Configuration in https://fit2.opendata.cz/resources/pipelines/created-1491043403748/graph/77
```
When I am positive that e.g.
```
<urn:uuid:0217e53d-1b2a-4105-ab77-b090012e9735> a <http://plugins.linkedpipes.com/ontology/t-sparqlSelectMultiple#Configuration> ;
	<http://plugins.linkedpipes.com/ontology/t-sparqlSelectMultiple#fileName> "http___data_semanticweb_org_sparql.csv" ;
	<http://plugins.linkedpipes.com/ontology/t-sparqlSelectMultiple#query> """
PREFIX adhoc: <http://linked.opendata.cz/ontology/adhoc/>
SELECT ?Class (SUM(?numberOfInstances) as ?instances)
WHERE {
  [] adhoc:class ?Class ;
    adhoc:numberOfInstances ?numberOfInstances ;
    adhoc:endpointUri \"http://data.semanticweb.org/sparql\" .
} GROUP BY ?Class
ORDER BY DESC(?instances) ASC(?Class)
""" .
```
was a valid configuration. Did the class and property prefix change?

**Comment by jakubklimek** [comment]
However, when I changed the configuration to ```http://plugins.linkedpipes.com/ontology/t-sparqlSelectMulti#Configuration```, it still says the same...

**Comment by jakubklimek** [comment]
```
2017-09-06 14:52:56,045 [asynchExecutor-1] ERROR c.l.e.e.e.Execution - Component execution failed : https://fit2.opendata.cz/resources/pipelines/created-1491043403748/15
com.linkedpipes.etl.executor.ExecutorException: Can't get configuration object of type http://plugins.linkedpipes.com/ontology/t-sparqlSelectMulti#Configuration in https://fit2.opendata.cz/resources/pipelines/created-1491043403748/graph/77
	at com.linkedpipes.etl.executor.component.configuration.Configuration.prepareConfiguration(Configuration.java:68)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.configureComponent(ExecuteComponent.java:163)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.initialize(ExecuteComponent.java:109)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.execute(ExecuteComponent.java:72)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponent(PipelineExecutor.java:253)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponents(PipelineExecutor.java:230)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:81)
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedpipes.etl.rdf.utils.InvalidNumberOfResults: Invalid number of results: 0 (1 expected) for:
SELECT ?resource WHERE { GRAPH <https://fit2.opendata.cz/resources/pipelines/created-1491043403748/graph/77> {
   ?resource a <http://plugins.linkedpipes.com/ontology/t-sparqlSelectMulti#Configuration>
} }
	at com.linkedpipes.etl.rdf.utils.RdfUtils.sparqlSelectSingle(RdfUtils.java:154)
	at com.linkedpipes.etl.executor.component.configuration.Configuration.prepareConfiguration(Configuration.java:65)
	... 10 common frames omitted
```
