### ISSUE TITLE
DCAT AP to CKAN

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/etl#522]
Hi, I am trying to test the DCAT AP to CKAN component.

The pipeline runs succesfully but the update never happens. I looked in the logs and found this

```
2017-12-24 02:14:06,282 [DCAT-AP to CKAN] ERROR c.l.p.l.d.DcatAp11ToCkan - Response:Found
2017-12-24 02:14:06,282 [DCAT-AP to CKAN] ERROR c.l.p.l.d.DcatAp11ToCkan - Error updating dataset
com.linkedpipes.etl.executor.api.v1.LpException: Error updating dataset
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:18)
	at com.linkedpipes.plugin.loader.dcatAp11ToCkan.DcatAp11ToCkan.execute(DcatAp11ToCkan.java:624)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	at java.lang.Thread.run(Thread.java:748)
```

from where to be honest I cannot get what is wrong. 

The only thing I could imagine is that the CKAN I use for testing (demo.ckan.org) does not allow API updates but I beleive that this would be stated explicitly. Any ideas?

**Comment by jakubklimek** [comment]
Hi, ok, this component was primarily for internal use, so it definitely does not cover all situations and errors.
Nevertheless, we use it regularly, with our CKAN instnace, so we should be able to make it work.
Could you give me access to the pipeline, or at least the full log? This indeed could be a CKAN api permission problem.

**Comment by skarampatakis** [comment]
Hi @jakubklimek! 
The pipeline is here. Is a minimal pipeline to test the functionality of the component.
[pipeline.zip](https://github.com/linkedpipes/etl/files/1584690/pipeline.zip)

I deployed LP to my local machine and spin up also a local instance of CKAN to test.

Now I am getting the following 
[pipeline2.zip](https://github.com/linkedpipes/etl/files/1584693/pipeline2.zip)

Is there any working example of CKAN-LP integration pipeline to check? Maybe I have misconfigured something. 

Merry Christmas!

**Comment by jakubklimek** [comment]
Hi, from pipeline.zip I think the problem is that there is no publisher specified. It should either be specified in DCAT-AP Dataset, or the organization ID overriden in DCAT-AP to CKAN. I will look into it more tomorrow. Merry Christmas!

**Comment by jakubklimek** [comment]
OK, I can confirm that it does not work with demo.ckan.org. Nevertheless, it works with our CKAN instances (not modified in any way). Not sure why demo.ckan.org says "JSON error" to our API calls. @skarampatakis can you test with your own instance?

**Comment by skarampatakis** [comment]
Hi @jakubklimek,
As I said above I already tested with my local CKAN instance getting another error. Perhaps I have misconfigured something. Do you have a sample working pipeline to test and close this issue? 

Actually, I found that x-httpRequest component is more useful to what I am trying to do, and currently working with this succesfully.

**Comment by jakubklimek** [comment]
OK, well, there is the sample pipeline available at https://etl.linkedpipes.com/components/l-dcatap11tockan. I [tried it now](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1514374351780&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2Ff604a5b7-0269-49e3-9079-6175be023fd1) and successfully created an organization and the [dataset in it](https://internal.opendata.cz/dataset/test9999). Here is the permissions part of our CKAN's production.ini you might want to check out:
```
## Authorization Settings

ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = true
ckan.auth.create_dataset_if_not_in_organization = true
ckan.auth.user_create_groups = true
ckan.auth.user_create_organizations = true
ckan.auth.user_delete_groups = true
ckan.auth.user_delete_organizations = true
ckan.auth.create_user_via_api = false
ckan.auth.create_user_via_web = false
ckan.auth.roles_that_cascade_to_sub_groups = admin
```

Glad that x-httpRequest works for you though.

**Comment by skarampatakis** [comment]
I loaded the pipeline on my local LP instance. 
Changed only the dataset id, action url and API key.
The pipeline runs succesfully but no resource is created. 
I get the same error 
```
2017-12-27 13:56:35,853 [DCAT-AP to CKAN] ERROR c.l.p.l.d.DcatAp11ToCkan - Response:"Bad request - JSON Error: Request data JSON decoded to None but it needs to be a dictionary."
2017-12-27 13:56:35,854 [DCAT-AP to CKAN] ERROR c.l.p.l.d.DcatAp11ToCkan - Error updating dataset
com.linkedpipes.etl.executor.api.v1.LpException: Error updating dataset
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:18)
	at com.linkedpipes.plugin.loader.dcatAp11ToCkan.DcatAp11ToCkan.execute(DcatAp11ToCkan.java:633)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:44)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
	at java.lang.Thread.run(Thread.java:748)
```

I changed the configuration of CKAN to match your own and restarted CKAN. Then I rerun the pipeline with the same result.
