### ISSUE TITLE
Executor-Monitor SLF4J failure

### ISSUE THREAD

**Issue by skodape** [linkedpipes/etl#58]
Sometimes executor-monitor log SLF4J failure:
```
SLF4J: Failed toString() invocation on an object of type [org.eclipse.jetty.server.HttpConnection]
java.lang.IndexOutOfBoundsException: 0
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
	at org.eclipse.jetty.util.BufferUtil.appendDebugString(BufferUtil.java:1038)
	at org.eclipse.jetty.util.BufferUtil.toDetailString(BufferUtil.java:1005)
	at org.eclipse.jetty.server.HttpConnection.toString(HttpConnection.java:785)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:297)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:269)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:227)
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:619)
	at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:206)
	at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:89)
	at org.eclipse.jetty.io.AbstractConnection.onClose(AbstractConnection.java:181)
	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:477)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:331)
	at org.eclipse.jetty.io.ManagedSelector$2.run(ManagedSelector.java:425)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.produceAndRun(ExecuteProduceRun.java:191)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.run(ExecuteProduceRun.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:641)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:559)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by skodape** [comment]
Have not seen this one for a while.
