### ISSUE TITLE
x-httpRequest gets stuck

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#590]
Log:
```
2018-08-22 05:39:44,066 [pool-186-thread-36] ERROR c.l.e.e.a.v.r.DefaultReportWriter - Task (http://vdp.cuzk.cz/vymenny_format/specialni/20180603_ST_UVOH.xml.gz) failed.
com.linkedpipes.etl.executor.api.v1.LpException: Request failed for: http://vdp.cuzk.cz/vymenny_format/specialni/20180603_ST_UVOH.xml.gz
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.exec.httprequest.TaskExecutor.performRequest(TaskExecutor.java:93)
	at com.linkedpipes.plugin.exec.httprequest.TaskExecutor.accept(TaskExecutor.java:62)
	at com.linkedpipes.plugin.exec.httprequest.TaskExecutor.accept(TaskExecutor.java:20)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:62)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:54)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:38)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1009)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at com.linkedpipes.plugin.exec.httprequest.Connection.finishRequest(Connection.java:38)
	at com.linkedpipes.plugin.exec.httprequest.TaskExecutor.performRequest(TaskExecutor.java:86)
	... 10 common frames omitted
2018-08-23 15:08:54,567 [asynchExecutor-1] DEBUG c.l.e.e.c.ExecuteComponent - Ignored interrupt.
java.lang.InterruptedException: null
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Thread.join(Thread.java:1353)
	at java.base/java.lang.Thread.join(Thread.java:1427)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.waitForThreadToFinish(ExecuteComponent.java:141)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.executeSequential(ExecuteComponent.java:132)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.execute(ExecuteComponent.java:119)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.execute(ExecuteComponent.java:75)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponent(PipelineExecutor.java:258)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponents(PipelineExecutor.java:235)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:81)
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:125)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by skodapetr** [comment]
@jakubklimek Is stil still issue as you are using the timeout option?

**Comment by jakubklimek** [comment]
Not sure as it is infrequent

**Comment by skodapetr** [comment]
Link to the execution or rest of the log?
