### ISSUE TITLE
Debug from fails

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#614]
Debug from fails with this in storage log:
```
2018-09-26 08:33:45,126 [web-server-2882] WARN  org.eclipse.jetty.server.HttpChannel - /api/v1/pipelines/unpack
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException: null
        at com.linkedpipes.etl.storage.unpacker.DesignerToExecutor.mapComponent(DesignerToExecutor.java:191)
        at com.linkedpipes.etl.storage.unpacker.DesignerToExecutor.mapExecution(DesignerToExecutor.java:180)
        at com.linkedpipes.etl.storage.unpacker.DesignerToExecutor.setPortMapping(DesignerToExecutor.java:158)
        at com.linkedpipes.etl.storage.unpacker.DesignerToExecutor.configurePorts(DesignerToExecutor.java:150)
        at com.linkedpipes.etl.storage.unpacker.DesignerToExecutor.transform(DesignerToExecutor.java:59)
        at com.linkedpipes.etl.storage.unpacker.UnpackerFacade.unpack(UnpackerFacade.java:75)
        at com.linkedpipes.etl.storage.unpacker.UnpackerFacade.unpack(UnpackerFacade.java:41)
        at com.linkedpipes.etl.storage.web.servlet.PipelineServlet.unpackPipeline(PipelineServlet.java:179)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        ... 28 common frames omitted
```

and this in executor-monitor log:
```
2018-09-26 03:24:33,529 [pool-1-thread-1] ERROR o.s.s.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: Not a valid (absolute) IRI: null
        at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:76)
        at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:65)
        at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:88)
        at com.linkedpipes.etl.rdf4j.Statements.addIri(Statements.java:59)
        at com.linkedpipes.etl.executor.monitor.execution.overview.OverviewToStatements.asStatements(OverviewToStatements.java:40)
        at com.linkedpipes.etl.executor.monitor.execution.LoadOverview.updateStatements(LoadOverview.java:136)
        at com.linkedpipes.etl.executor.monitor.execution.LoadOverview.updateExecutionFromOverview(LoadOverview.java:64)
        at com.linkedpipes.etl.executor.monitor.execution.LoadOverview.load(LoadOverview.java:55)
        at com.linkedpipes.etl.executor.monitor.execution.LoadOverview.load(LoadOverview.java:37)
        at com.linkedpipes.etl.executor.monitor.execution.ExecutionStorage.update(ExecutionStorage.java:157)
        at com.linkedpipes.etl.executor.monitor.execution.ExecutionStorage.updateExecutions(ExecutionStorage.java:274)
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

![image](https://user-images.githubusercontent.com/718827/46073902-735c3000-c186-11e8-9a68-7ec435b0dbdf.png)

**Comment by skodapetr** [comment]
The executor monitor exception has nothing to do with that. I take a look at the first provided exception, however without an execution it may not be of any use.

**Comment by skodapetr** [comment]
Ok, from the exception is not clear why the error happens, the image is not helping. Without further information, I'm afraid I'm not able to fix this.
