### ISSUE TITLE
Graph store protocol loader: Method not implemented

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#636]
[Using this pipeline](https://github.com/linkedpipes/etl/files/2572573/04.-.Nahrani.do.databaze.Virtuoso.jsonld.txt) I get ```Can't upload data, reason: Method Not Implemented``` which is not very useful:
```
https://etl.csu.opendata.cz/resources/pipelines/1542037700694/components/05791bed-da18-4d55-b9fc-23185bfb8c9b
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:39)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:34)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't upload data, reason: Method Not Implemented
at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
at com.linkedpipes.plugin.loader.graphstoreprotocol.GraphStoreProtocol.executeHttp(GraphStoreProtocol.java:306)
at com.linkedpipes.plugin.loader.graphstoreprotocol.GraphStoreProtocol.uploadVirtuoso(GraphStoreProtocol.java:251)
at com.linkedpipes.plugin.loader.graphstoreprotocol.GraphStoreProtocol.execute(GraphStoreProtocol.java:113)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:37)
... 2 common frames omitted
```

**Comment by jakubklimek** [comment]
Actually, it is just a wrong endpoint URI (grap instead of graph) but the error message is unhelpful

**Comment by skodapetr** [comment]
```Method not implemented``` is a response as provided by the server.
The exception message was updated to emphasize that fact.
