### ISSUE TITLE
Executor cannot start

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#667]
Executor cannot start, this is in the log:
```
2019-02-13 10:30:45,878 [main] ERROR com.linkedpipes.etl.executor.module.ModuleService - Can't start bundle: org.apache.jena.osgi
org.osgi.framework.BundleException: Could not resolve module: org.apache.jena.osgi [1]
  Unresolved requirement: Import-Package: javax.annotation
  Unresolved requirement: Import-Package: com.github.jsonldjava.core; version="[0.12.0,1.0.0)"
    -> Export-Package: com.github.jsonldjava.core; bundle-symbolic-name="com.github.jsonld-java"; bundle-version="0.12.0"; version="0.12.0"; uses:="org.apache.http.impl.client"
       com.github.jsonld-java [34]
         Unresolved requirement: Import-Package: org.apache.http; version="[4.4.0,5.0.0)"
           -> Export-Package: org.apache.http; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http.params,org.apache.http.protocol,org.apache.http.util"
              org.apache.httpcomponents.httpcore [16]
                No resolution report for the bundle.         Unresolved requirement: Import-Package: com.google.common.cache; version="[24.1.0,25.0.0)"
           -> Export-Package: com.google.common.cache; bundle-symbolic-name="com.google.guava"; bundle-version="24.1.0.jre"; version="24.1.0"; uses:="com.google.common.base,com.google.common.collect,com.google.common.util.concurrent"
              com.google.guava [12]
                Unresolved requirement: Import-Package: javax.annotation; resolution:="optional"
         Unresolved requirement: Import-Package: com.fasterxml.jackson.databind; version="[2.9.0,3.0.0)"
           -> Export-Package: com.fasterxml.jackson.databind; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-databind"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.core.filter,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.type,com.fasterxml.jackson.databind.annotation,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.deser,com.fasterxml.jackson.databind.deser.impl,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsonFormatVisitors,com.fasterxml.jackson.databind.jsonschema,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.jsontype.impl,com.fasterxml.jackson.databind.node,com.fasterxml.jackson.databind.ser,com.fasterxml.jackson.databind.ser.impl,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util"
              com.fasterxml.jackson.core.jackson-databind [36]
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.json; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.json; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.core.base,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.sym"
                     com.fasterxml.jackson.core.jackson-core [2]
                       No resolution report for the bundle.                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.type; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.type; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.util; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.util; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.core.io"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.io; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.io; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.core.util"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.base; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.base; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.json,com.fasterxml.jackson.core.util"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.format; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.format; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core.filter; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core.filter; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.core.util"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core.async,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.sym,com.fasterxml.jackson.core.type,com.fasterxml.jackson.core.util"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.annotation; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-annotations"; bundle-version="2.9.6"; version="2.9.6"
                     com.fasterxml.jackson.core.jackson-annotations [8]
                       No resolution report for the bundle.         Unresolved requirement: Import-Package: org.apache.http.impl.client; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.impl.client; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="javax.net.ssl,org.apache.commons.logging,org.apache.http,org.apache.http.auth,org.apache.http.client,org.apache.http.client.config,org.apache.http.client.entity,org.apache.http.client.methods,org.apache.http.concurrent,org.apache.http.config,org.apache.http.conn,org.apache.http.conn.routing,org.apache.http.conn.socket,org.apache.http.conn.ssl,org.apache.http.conn.util,org.apache.http.cookie,org.apache.http.impl,org.apache.http.impl.auth,org.apache.http.impl.execchain,org.apache.http.message,org.apache.http.params,org.apache.http.pool,org.apache.http.protocol"
              org.apache.httpcomponents.httpclient [32]
                Unresolved requirement: Import-Package: net.sf.ehcache; resolution:="optional"
                Unresolved requirement: Import-Package: net.spy.memcached; resolution:="optional"
                Unresolved requirement: Import-Package: org.apache.http.io; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.io; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.config,org.apache.http.util"
                Unresolved requirement: Import-Package: org.osgi.service.cm; version="[1.3.0,2.0.0)"
                  -> Export-Package: org.osgi.service.cm; bundle-symbolic-name="osgi.cmpn"; bundle-version="5.0.0.201305092017"; version="1.5.0"; uses:="org.osgi.framework"
                     osgi.cmpn [28]
                       Unresolved requirement: Import-Package: javax.microedition.io; resolution:="optional"
                       Unresolved requirement: Import-Package: javax.persistence; resolution:="optional"
                       Unresolved requirement: Import-Package: org.osgi.framework; resolution:="optional"
                         -> Export-Package: org.osgi.framework; bundle-symbolic-name="osgi.core"; bundle-version="5.0.0.201203141902"; version="1.7.0"; uses:="javax.security.auth.x500"
                            osgi.core [23]
                              No resolution report for the bundle.                       Unresolved requirement: Import-Package: org.osgi.resource; resolution:="optional"
                         -> Export-Package: org.osgi.resource; bundle-symbolic-name="osgi.core"; bundle-version="5.0.0.201203141902"; version="1.0.0"
                Unresolved requirement: Import-Package: org.apache.http.impl.entity; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.impl.entity; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.entity,org.apache.http.io"
                Unresolved requirement: Import-Package: org.apache.commons.logging; version="[1.1.0,1.3.0)"
                  -> Export-Package: org.apache.commons.logging; bundle-symbolic-name="org.apache.commons.logging"; bundle-version="1.1.1.v201101211721"; version="1.1.1"
                     org.apache.commons.logging [21]
                       No resolution report for the bundle.                Unresolved requirement: Import-Package: org.apache.http; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http.params,org.apache.http.protocol,org.apache.http.util"
                Unresolved requirement: Import-Package: org.apache.http.entity; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.entity; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http"
                Unresolved requirement: Import-Package: org.apache.http.pool; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.pool; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http.concurrent"
                Unresolved requirement: Import-Package: org.apache.http.protocol; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.protocol; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.params"
                Unresolved requirement: Import-Package: org.apache.http.message; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.message; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.params,org.apache.http.util"
                Unresolved requirement: Import-Package: org.apache.http.concurrent; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.concurrent; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"
                Unresolved requirement: Import-Package: org.apache.http.impl; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.impl; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.config,org.apache.http.entity,org.apache.http.impl.entity,org.apache.http.io,org.apache.http.params,org.apache.http.protocol"
                Unresolved requirement: Import-Package: org.osgi.framework; version="[1.5.0,2.0.0)"
                  -> Export-Package: org.osgi.framework; bundle-symbolic-name="osgi.core"; bundle-version="5.0.0.201203141902"; version="1.7.0"; uses:="javax.security.auth.x500"
                Unresolved requirement: Import-Package: org.apache.http.params; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.params; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.config"
                Unresolved requirement: Import-Package: org.apache.http.impl.io; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.impl.io; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.config,org.apache.http.io,org.apache.http.message,org.apache.http.params,org.apache.http.util"
                Unresolved requirement: Import-Package: org.apache.http.config; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.config; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"
                Unresolved requirement: Import-Package: org.apache.http.ssl; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.ssl; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="javax.net.ssl"
                Unresolved requirement: Import-Package: org.apache.http.util; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.util; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http"
                Unresolved requirement: Import-Package: org.apache.http.impl.pool; version="[4.4.0,4.5.0)"
                  -> Export-Package: org.apache.http.impl.pool; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="javax.net,javax.net.ssl,org.apache.http,org.apache.http.config,org.apache.http.params,org.apache.http.pool"
         Unresolved requirement: Import-Package: org.apache.http.client.protocol; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.client.protocol; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.auth,org.apache.http.client,org.apache.http.client.config,org.apache.http.client.entity,org.apache.http.config,org.apache.http.conn.routing,org.apache.http.cookie,org.apache.http.protocol"
         Unresolved requirement: Import-Package: org.apache.http.client; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.client; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.auth,org.apache.http.client.methods,org.apache.http.conn,org.apache.http.conn.routing,org.apache.http.cookie,org.apache.http.params,org.apache.http.protocol"
         Unresolved requirement: Import-Package: com.google.common.collect; version="[24.1.0,25.0.0)"
           -> Export-Package: com.google.common.collect; bundle-symbolic-name="com.google.guava"; bundle-version="24.1.0.jre"; version="24.1.0"; uses:="com.google.common.base"
         Unresolved requirement: Import-Package: org.apache.http.client.cache; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.client.cache; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client.protocol,org.apache.http.protocol"
         Unresolved requirement: Import-Package: org.apache.http.impl.client.cache; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.impl.client.cache; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client,org.apache.http.client.cache,org.apache.http.client.methods,org.apache.http.client.protocol,org.apache.http.conn,org.apache.http.conn.routing,org.apache.http.impl.client,org.apache.http.impl.execchain,org.apache.http.params,org.apache.http.protocol"
         Unresolved requirement: Import-Package: org.apache.http.client.utils; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.client.utils; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client,org.apache.http.client.methods,org.apache.http.conn.routing,org.apache.http.util"
         Unresolved requirement: Import-Package: org.apache.commons.io.input; version="[1.4.0,2.0.0)"
           -> Export-Package: org.apache.commons.io.input; bundle-symbolic-name="org.apache.commons.io"; bundle-version="2.5.0"; version="1.4.9999"
              org.apache.commons.io [35]
                No resolution report for the bundle.         Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,2.0.0)"
           -> Export-Package: org.apache.commons.io; bundle-symbolic-name="org.apache.commons.io"; bundle-version="2.5.0"; version="1.4.9999"
         Unresolved requirement: Import-Package: com.github.jsonldjava.utils
           -> Export-Package: com.github.jsonldjava.utils; bundle-symbolic-name="com.github.jsonld-java"; bundle-version="0.11.0"; version="0.11.0"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.databind,org.apache.http.client.cache,org.apache.http.impl.client,org.apache.http.impl.client.cache"
              com.github.jsonld-java [44]
                Unresolved requirement: Import-Package: com.fasterxml.jackson.databind; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.databind; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-databind"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.core.filter,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.type,com.fasterxml.jackson.databind.annotation,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.deser,com.fasterxml.jackson.databind.deser.impl,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsonFormatVisitors,com.fasterxml.jackson.databind.jsonschema,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.jsontype.impl,com.fasterxml.jackson.databind.node,com.fasterxml.jackson.databind.ser,com.fasterxml.jackson.databind.ser.impl,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util"
                Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,2.0.0)"
                  -> Export-Package: org.apache.commons.io; bundle-symbolic-name="org.apache.commons.io"; bundle-version="2.5.0"; version="1.4.9999"
                Unresolved requirement: Import-Package: org.apache.http.client.methods; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.client.methods; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client.config,org.apache.http.concurrent,org.apache.http.conn,org.apache.http.message,org.apache.http.params"
                Unresolved requirement: Import-Package: org.apache.http.client; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.client; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.auth,org.apache.http.client.methods,org.apache.http.conn,org.apache.http.conn.routing,org.apache.http.cookie,org.apache.http.params,org.apache.http.protocol"
                Unresolved requirement: Import-Package: org.apache.http.client.protocol; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.client.protocol; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.auth,org.apache.http.client,org.apache.http.client.config,org.apache.http.client.entity,org.apache.http.config,org.apache.http.conn.routing,org.apache.http.cookie,org.apache.http.protocol"
                Unresolved requirement: Import-Package: org.apache.http; version="[4.4.0,5.0.0)"
                  -> Export-Package: org.apache.http; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http.params,org.apache.http.protocol,org.apache.http.util"
                Unresolved requirement: Import-Package: org.apache.http.message; version="[4.4.0,5.0.0)"
                  -> Export-Package: org.apache.http.message; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.params,org.apache.http.util"
                Unresolved requirement: Import-Package: org.apache.http.client.cache; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.client.cache; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client.protocol,org.apache.http.protocol"
                Unresolved requirement: Import-Package: org.apache.http.impl.client.cache; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.impl.client.cache; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client,org.apache.http.client.cache,org.apache.http.client.methods,org.apache.http.client.protocol,org.apache.http.conn,org.apache.http.conn.routing,org.apache.http.impl.client,org.apache.http.impl.execchain,org.apache.http.params,org.apache.http.protocol"
                Unresolved requirement: Import-Package: org.apache.http.impl.client; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.impl.client; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="javax.net.ssl,org.apache.commons.logging,org.apache.http,org.apache.http.auth,org.apache.http.client,org.apache.http.client.config,org.apache.http.client.entity,org.apache.http.client.methods,org.apache.http.concurrent,org.apache.http.config,org.apache.http.conn,org.apache.http.conn.routing,org.apache.http.conn.socket,org.apache.http.conn.ssl,org.apache.http.conn.util,org.apache.http.cookie,org.apache.http.impl,org.apache.http.impl.auth,org.apache.http.impl.execchain,org.apache.http.message,org.apache.http.params,org.apache.http.pool,org.apache.http.protocol"
                Unresolved requirement: Import-Package: org.apache.http.client.utils; version="[4.5.0,5.0.0)"
                  -> Export-Package: org.apache.http.client.utils; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client,org.apache.http.client.methods,org.apache.http.conn.routing,org.apache.http.util"
                Unresolved requirement: Import-Package: com.fasterxml.jackson.core; version="[2.9.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.core; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core.async,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.sym,com.fasterxml.jackson.core.type,com.fasterxml.jackson.core.util"
         Unresolved requirement: Import-Package: org.apache.http.message; version="[4.4.0,5.0.0)"
           -> Export-Package: org.apache.http.message; bundle-symbolic-name="org.apache.httpcomponents.httpcore"; bundle-version="4.4.4"; version="4.4.4"; uses:="org.apache.http,org.apache.http.params,org.apache.http.util"
         Unresolved requirement: Import-Package: com.fasterxml.jackson.core; version="[2.9.0,3.0.0)"
           -> Export-Package: com.fasterxml.jackson.core; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core.async,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.sym,com.fasterxml.jackson.core.type,com.fasterxml.jackson.core.util"
         Unresolved requirement: Import-Package: org.apache.http.client.methods; version="[4.5.0,5.0.0)"
           -> Export-Package: org.apache.http.client.methods; bundle-symbolic-name="org.apache.httpcomponents.httpclient"; bundle-version="4.5.2"; version="4.5.2"; uses:="org.apache.http,org.apache.http.client.config,org.apache.http.concurrent,org.apache.http.conn,org.apache.http.message,org.apache.http.params"
  Unresolved requirement: Import-Package: com.github.jsonldjava.utils; version="[0.12.0,1.0.0)"
    -> Export-Package: com.github.jsonldjava.utils; bundle-symbolic-name="com.github.jsonld-java"; bundle-version="0.12.0"; version="0.12.0"; uses:="com.fasterxml.jackson.core,com.fasterxml.jackson.databind,org.apache.http.client.cache,org.apache.http.impl.client,org.apache.http.impl.client.cache"
  Unresolved requirement: Import-Package: org.osgi.framework; version="[1.7.0,2.0.0)"
    -> Export-Package: org.osgi.framework; bundle-symbolic-name="osgi.core"; bundle-version="5.0.0.201203141902"; version="1.7.0"; uses:="javax.security.auth.x500"
  Unresolved requirement: Import-Package: com.fasterxml.jackson.databind; version="[2.9.0,3.0.0)"
    -> Export-Package: com.fasterxml.jackson.databind; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-databind"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.core.filter,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.type,com.fasterxml.jackson.databind.annotation,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.deser,com.fasterxml.jackson.databind.deser.impl,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsonFormatVisitors,com.fasterxml.jackson.databind.jsonschema,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.jsontype.impl,com.fasterxml.jackson.databind.node,com.fasterxml.jackson.databind.ser,com.fasterxml.jackson.databind.ser.impl,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util"
  Unresolved requirement: Import-Package: com.fasterxml.jackson.core; version="[2.9.0,3.0.0)"
    -> Export-Package: com.fasterxml.jackson.core; bundle-symbolic-name="com.fasterxml.jackson.core.jackson-core"; bundle-version="2.9.6"; version="2.9.6"; uses:="com.fasterxml.jackson.core.async,com.fasterxml.jackson.core.format,com.fasterxml.jackson.core.io,com.fasterxml.jackson.core.sym,com.fasterxml.jackson.core.type,com.fasterxml.jackson.core.util"
  Unresolved requirement: Import-Package: com.github.andrewoma.dexx.collection
    -> Export-Package: com.github.andrewoma.dexx.collection; bundle-symbolic-name="com.github.andrewoma.dexx.collection"; bundle-version="0.7.0"; version="0.0.0"
       com.github.andrewoma.dexx.collection [18]
         No resolution report for the bundle.
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
        at com.linkedpipes.etl.executor.module.ModuleService.startBundle(ModuleService.java:292)
        at com.linkedpipes.etl.executor.module.ModuleService.lambda$loadLibraries$2(ModuleService.java:274)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.linkedpipes.etl.executor.module.ModuleService.loadLibraries(ModuleService.java:274)
        at com.linkedpipes.etl.executor.module.ModuleService.start(ModuleService.java:255)
        at com.linkedpipes.etl.executor.module.ModuleService.onApplicationEvent(ModuleService.java:212)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
        at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1306)
        at com.linkedpipes.etl.executor.Executor.startExecutorService(Executor.java:37)
        at com.linkedpipes.etl.executor.Executor.main(Executor.java:41)
2019-02-13 10:30:45,987 [main] INFO  com.linkedpipes.etl.executor.web.WebServer - Closing web server ...
2019-02-13 10:30:45,987 [main] INFO  com.linkedpipes.etl.executor.web.WebServer - Closing web server ... done
2019-02-13 10:30:45,988 [Thread-0] INFO  o.s.context.support.ClassPathXmlApplicationContext - Closing org.springframework.context.support.ClassPathXmlApplicationContext@2b71e916: startup date [Wed Feb 13 10:30:44 CET 2019]; root of context hierarchy
2019-02-13 10:30:45,990 [Thread-0] INFO  o.s.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService
```

**Comment by skodapetr** [comment]
Is it reproducible?
Have you clear the deploy directory (just keep the configuration)-

**Comment by jakubklimek** [comment]
Hm... clearing the deploy directory helped.

**Comment by skodapetr** [comment]
We it's because the deploy directory (OSGI) is not cleared on clean on ```mvn clean```. You can create another issue for this.
