### ISSUE TITLE
Wikibase loader fails on Wikidata insance

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#725]
[This](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565340923582&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1565351280215-129-97c88318-a2fe-41b9-abf5-b3cf212cdf3e) pipeline should update the label of the sandbox Wikidata item. However, it fails on
```
com.linkedpipes.etl.executor.api.v1.LpException: Error processing document: http://www.wikidata.org/entity/Q4115189
at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:79)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:18)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [no-external-page] The external client site "zhwikivoyage" did not provide page information for page "Wikivoyage:涂鸦墙/维基数据".
at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:62)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:459)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:399)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:294)
at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.editItemDocument(WikibaseDataEditor.java:315)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.saveDocumentChanges(DocumentSynchronizer.java:296)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.synchronize(DocumentSynchronizer.java:109)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:77)
... 9 common frames omitted
```
, and then on
```
2019-08-09 13:48:03,588 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://etl.opendata.cz/resources/pipelines/1565340923582/component/2141-ae61
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't close connection.
at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.closeConnection(WikibaseWorker.java:96)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onAfterExecution(WikibaseWorker.java:86)
at com.linkedpipes.plugin.loader.wikibase.WikibaseLoader.afterExecution(WikibaseLoader.java:96)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecution.execute(TaskExecution.java:61)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
Caused by: java.io.IOException: [notoken] The "token" parameter must be set.
at org.wikidata.wdtk.wikibaseapi.ApiConnection.logout(ApiConnection.java:337)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.closeConnection(WikibaseWorker.java:94)
... 6 common frames omitted
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.TokenErrorException: [notoken] The "token" parameter must be set.
at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:54)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:459)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:399)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.logout(ApiConnection.java:335)
... 7 common frames omitted
```

**Comment by jakubklimek** [comment]
This may also be due to an inconsistent state of the Wikibase sandbox item due to previous edits of different clients...

**Comment by jakubklimek** [comment]
Ok, this is probalby because of a broken sitelink:
![image](https://user-images.githubusercontent.com/718827/62778145-e70ddf80-baaf-11e9-872b-34837fa0cbb7.png)
