### ISSUE TITLE
Wikibase loader: Display more meaningful errors

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#727]
When loading using the wikibase loader fails, the error displayed is not the important one. I see:
![image](https://user-images.githubusercontent.com/718827/62778313-5e437380-bab0-11e9-8aa2-0d7381093e04.png)
In the log, there is:
```
com.linkedpipes.etl.executor.api.v1.LpException: Error processing document: http://www.wikidata.org/entity/Q4115189
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:79)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:18)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [modification-failed] Label and description for language code ku-latn can not have the same value.
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:62)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:459)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:399)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:294)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.editItemDocument(WikibaseDataEditor.java:315)
	at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.saveDocumentChanges(DocumentSynchronizer.java:296)
	at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.synchronize(DocumentSynchronizer.java:109)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:77)
	... 9 common frames omitted
2019-08-09 14:14:08,231 [Wikibase loader] INFO  c.l.e.e.e.ExecutionObserver - onComponentUserCodeFailed : https://etl.opendata.cz/resources/pipelines/1565340923582/component/2141-ae61
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser - onComponentExecuted
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser - Close data units:
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/2141-ae61/port/Configuration : Configuration
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE MAPPED t/194c-9670/port/Configuration : Configuration
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/2141-ae61/port/InputRdf : InputRdf
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/2141-ae61/port/OutputRdf : OutputRdf
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE MAPPED t/194c-9670/port/InputFiles : InputFiles
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/2141-ae61/port/ReportRdf : ReportRdf
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         MAPPED t/0973-9b62/port/FilesOutput : FilesOutput
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/194c-9670/port/OutputRdf : OutputRdf
2019-08-09 14:14:08,235 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (5)
2019-08-09 14:14:08,235 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2019-08-09 14:14:08,236 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2019-08-09 14:14:08,236 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (4)
2019-08-09 14:14:08,236 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2019-08-09 14:14:08,236 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (3)
2019-08-09 14:14:08,236 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2019-08-09 14:14:08,236 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (2)
2019-08-09 14:14:08,236 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2019-08-09 14:14:08,236 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (1)
2019-08-09 14:14:08,236 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Closing repository group: single (0) ... 
2019-08-09 14:14:08,236 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - Shutting down NativeStore...
2019-08-09 14:14:08,236 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - NativeStore shut down
2019-08-09 14:14:08,236 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - NativeStore shut down
2019-08-09 14:14:08,236 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Closing repository ... done
2019-08-09 14:14:08,237 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://etl.opendata.cz/resources/pipelines/1565340923582/component/2141-ae61
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't close connection.
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.closeConnection(WikibaseWorker.java:96)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onAfterExecution(WikibaseWorker.java:86)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseLoader.afterExecution(WikibaseLoader.java:96)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecution.execute(TaskExecution.java:61)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
Caused by: java.io.IOException: [notoken] The "token" parameter must be set.
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.logout(ApiConnection.java:337)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.closeConnection(WikibaseWorker.java:94)
	... 6 common frames omitted
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.TokenErrorException: [notoken] The "token" parameter must be set.
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:54)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:459)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:399)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.logout(ApiConnection.java:335)
	... 7 common frames omitted
```
The first exception is the meaningful one. Maybe both should be displayed in the dialog.

**Comment by skodapetr** [comment]
We have a requirement where the root exception needs to be shown.
So now you would like to see the root and the top exception as well? Or just the top exception, i.e. extra behavior just for this single component.

**Comment by jakubklimek** [comment]
The goal is to show what is meaningful. This might be different in each case.

**Comment by skodapetr** [comment]
That is not exactly an answer, so only for the component a top message, instead of or root message, should be shown?

**Comment by jakubklimek** [comment]
Thats because there might not be such a generic rule. The user does not care about what is top and what is root. In this case, the exception shown was not the correct one to show.

**Comment by skodapetr** [comment]
The error message is actually ok in this case as the loading of a document is just a task, while the closing of the connection is a component-level issue as visible in #728.

**Comment by jakubklimek** [comment]
Does this mean that when #728 is solved, the task error will be visible? Currently, the user needs to go to the detailed log to see the message, which is what should be made easier.

**Comment by jakubklimek** [comment]
OK, I see, instead of this error, there will be the generic "at least one task failed" error. Maybe this should be a more generic issue of displaying the task error, when the component fails on it, directly in the dialog.
