### ISSUE TITLE
Wikibase loader: Can't close connection error after loading to Wikidata

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#728]
After loading to Wikidata (even successfully), the component fails on:
```
https://etl.opendata.cz/resources/pipelines/1565340923582/component/2141-ae61
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't close connection.
at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.closeConnection(WikibaseWorker.java:96)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onAfterExecution(WikibaseWorker.java:86)
at com.linkedpipes.plugin.loader.wikibase.WikibaseLoader.afterExecution(WikibaseLoader.java:96)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecution.execute(TaskExecution.java:61)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
Caused by: java.io.IOException: [notoken] The "token" parameter must be set.
at org.wikidata.wdtk.wikibaseapi.ApiConnection.logout(ApiConnection.java:337)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.closeConnection(WikibaseWorker.java:94)
... 6 common frames omitted
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.TokenErrorException: [notoken] The "token" parameter must be set.
at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:54)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:459)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:399)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.logout(ApiConnection.java:335)
... 7 common frames omitted
```

**Comment by skodapetr** [comment]
How long was the component execution? Home many entities were created/modified?

**Comment by jakubklimek** [comment]
Just one item. See (try) [this](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565340923582&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1565353578981-141-351869a5-be2d-4311-b73e-ad3907168bb8)

**Comment by skodapetr** [comment]
Have you tested this one on our local instance? Can it be that our instance is of the older version?

**Comment by jakubklimek** [comment]
Yes, our instance can be an older version. Thats why I also tested the Wikidata instance

**Comment by skodapetr** [comment]
The same issue was reproducible with minimal code and is probably caused by the used library.
I've created the https://github.com/Wikidata/Wikidata-Toolkit/issues/428 that should help us solve this.
