### ISSUE TITLE
Files to SCP: improve error message for insufficient file permissions

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#73]
When Files to SCP doesn't have sufficient file permissions (e.g., the user configured in the DPU cannot overwrite already loaded file), pipeline fails and presents a vague error:

```
Reason:
 Component execution failed! 
Exception:
 com.linkedpipes.etl.executor.api.v1.component.Component$ComponentFailed: Component failed!
    at com.linkedpipes.etl.dpu.component.SequentialComponent.execute(SequentialComponent.java:282)
    at com.linkedpipes.executor.execution.contoller.ComponentExecutor.run(ComponentExecutor.java:130)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.linkedpipes.etl.dpu.api.DataProcessingUnit$ExecutionFailed: Error: {}
    at com.linkedpipes.plugin.loader.scp.LoaderScp.resonseCheck(LoaderScp.java:240)
    at com.linkedpipes.plugin.loader.scp.LoaderScp.sendFile(LoaderScp.java:208)
    at com.linkedpipes.plugin.loader.scp.LoaderScp.sendDirectoryContent(LoaderScp.java:148)
    at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:89)
    at com.linkedpipes.etl.dpu.component.SequentialComponent.execute(SequentialComponent.java:263)
    ... 2 more
```

The error message can be improved and explicitly mentioned that the error was caused by insufficient file permissions.

**Comment by jakubklimek** [comment]
I think this has been improved already. @skodapetr @jindrichmynarz can you check?

**Comment by jindrichmynarz** [comment]
Yes. In 1e3c5ba7aa3be3df84e9580d32cfe69444a76f3e this throws `LpException : Error: scp: path/to/file.txt: Permission denied`.
