### ISSUE TITLE
Importing pipelines with templates fails

### ISSUE THREAD

**Issue by rizktouma** [linkedpipes/etl#732]
I am trying to import pipelines that I have created on another instance of LinkedPipes and that use component templates. Both instances use the same URL scheme.

The pipeline gets imported to the new instance, but when I go to edit mode I see that the pipeline is messed up and all component templates are missing. Moreover, in the "Templates" tab of the interface, none of the templates used by the pipelines is imported and it remains empty.

I also tried manually copying the templates I created to the "deploy" folder of the new instance, but this is also failing with the error "Cannot load component because configuration-description.trig does not exist".

What am I doing wrong?

**Comment by jakubklimek** [comment]
The key here is to make sure you exported the pipelines with templates, e.g. not the "backup without templates" option. Can you share the export with us?

Do you know the versions of both instances, i.e. source and target?

**Comment by rizktouma** [comment]
I am importing the pipeline definition file ".trig" found in the `./deploy/data/pipelines` directory to the new instance directly. The idea is I want the instance to run with the pipelines I defined, without needing to "import" each of them through the interface.

If the pipeline don't have any templates, then this works fine and the new instance reads the pipelines correctly. My only problem is when the pipelines are based on templates, which I can't find a way to add to the "deploy" directory without causing errors.

**Comment by jakubklimek** [comment]
That file indeed does not contain templates. Those are in `{storage}/templates`. If you copy those too, it should work.

**Comment by rizktouma** [comment]
Apologies for the late reply I was away for the summer. I just tested it copying both `/pipelines` and `/templates` into the `/deploy` directory and it works correctly. Thanks for the help.

**Comment by jakubklimek** [comment]
@rizktouma Any particular reason for reopening this?

**Comment by rizktouma** [comment]
Yes, I am still facing an issue when importing templates.

I'm trying to create a docker image with LinkedPipes. After compiling the tool and creating the `./deploy` directory, I have a script that automatically copies some pipelines and templates that I have created into that directory.

The compilation works correctly but when I try to run LP, I get the following error:

`ERROR c.linkedpipes.etl.storage.template.TemplateManager - Migration of component 'http://localhost:32800/resources/components/1563183926701-84f3fb70-a598-4745-a27d-92e8ef3fc6d2' failed`

The "component" it is trying to load is actually one of the templates I have created. I attached the [definition.trig](https://github.com/linkedpipes/etl/files/3701927/definition.trig.zip) file just in case, but it is a very simple template based on the `t-sparqlConstruct` component. Note that I get the same error for all of the templates that I am trying to import.

It seems to me that the problem is that the first time I run LP, the "templates" directory does not contain any of the folders refering to the components (e.g. `jar-t-sparqlConstruct-0.0.0.jar`), so it cannot create any templates based on these components. If I run LP once without templates, these folders are created and then importing the templates afterwards seems to work.

Is there a way to avoid this? In my case I need to have all of the templates before starting LP the first time.

The full stack trace of the error is the following:
`com.linkedpipes.etl.storage.rdf.RdfUtils$RdfException: 
	at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:231)
	at com.linkedpipes.etl.storage.template.repository.TemplateRepository.getConfigDescription(TemplateRepository.java:92)
	at com.linkedpipes.etl.storage.template.TemplateV1ToV2.updateConfigDescription(TemplateV1ToV2.java:118)
	at com.linkedpipes.etl.storage.template.TemplateV1ToV2.updateConfigDescriptionReference(TemplateV1ToV2.java:83)
	at com.linkedpipes.etl.storage.template.TemplateV1ToV2.migrate(TemplateV1ToV2.java:49)
	at com.linkedpipes.etl.storage.template.TemplateManager.lambda$migrateV1ToV2$0(TemplateManager.java:169)
	at com.linkedpipes.etl.storage.template.TemplateManager.migrateTemplates(TemplateManager.java:179)
	at com.linkedpipes.etl.storage.template.TemplateManager.migrateV1ToV2(TemplateManager.java:168)
	at com.linkedpipes.etl.storage.template.TemplateManager.migrate(TemplateManager.java:148)
	at com.linkedpipes.etl.storage.template.TemplateManager.initialize(TemplateManager.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1623)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.linkedpipes.etl.storage.Storage.main(Storage.java:101)
Caused by: java.io.FileNotFoundException: ./data/templates/1563183926701-84f3fb70-a598-4745-a27d-92e8ef3fc6d2/configuration-description.trig (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:228)
	... 58 common frames omitted`

**Comment by jakubklimek** [comment]
@skodapetr is also working on LP-ETL in docker. Maybe he can give you some tips regarding this

**Comment by rizktouma** [comment]
I've narrowed down the error to the fact that `com.linkedpipes.etl.storage.template.repository..TemplateRepository.getConfigDescription(
            RepositoryReference ref)` tries to read a file named `configuration-description.trig`, which exists in the component folders inside `deploy/data/templates`, but does not exist for the templates.

**Comment by rizktouma** [comment]
So I found a workaround to avoid this problem. If I want to start LP-ETL with some pre-defined templates that I copy into `deploy/data/templates`, I should also copy the `repository-info.json` file to the same directory **before** starting LP-ETL.

This way, executing `./storage.sh` to start LP generates the templates of the components in the `deploy/jars` directory but does not start the template "migration" process, which is what was causing the error I mentioned above.

This feels like kind of a hacky fix, so I'll keep the issue open to get a better response from you.

**Comment by skodapetr** [comment]
It should now be possible to just copy files from one instance to another. In addition it is possible to use import/export functionality to transfer pipelines and templates between instances.
