### ISSUE TITLE
Wikibase loader fails on "Wikibase property" data type

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#737]
See [this pipeline](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565792536575&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1565792603317-184-03ad826d-8eca-4315-b34d-e5d2822de68e). It fails on Wikibase property data type:
```
MediaWikiApiErrorException : [modification-failed] Bad value type string, expected wikibase-entityid
```

**Comment by jakubklimek** [comment]
Now when I actually want to change the value from P17 to P16, I get:
```
java.lang.IllegalArgumentException: Entity id "https://wikibase.opendata.cz/entity/P16" is not supported.
at org.wikidata.wdtk.datamodel.implementation.EntityIdValueImpl.guessEntityTypeFromId(EntityIdValueImpl.java:160)
at org.wikidata.wdtk.datamodel.implementation.EntityIdValueImpl$JacksonInnerEntityId.<init>(EntityIdValueImpl.java:220)
at org.wikidata.wdtk.datamodel.implementation.EntityIdValueImpl.<init>(EntityIdValueImpl.java:90)
at org.wikidata.wdtk.datamodel.implementation.PropertyIdValueImpl.<init>(PropertyIdValueImpl.java:59)
at org.wikidata.wdtk.datamodel.implementation.DataObjectFactoryImpl.getPropertyIdValue(DataObjectFactoryImpl.java:48)
at org.wikidata.wdtk.datamodel.helpers.Datamodel.makeWikidataPropertyIdValue(Datamodel.java:99)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.createSimpleValue(DocumentSynchronizer.java:315)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.synchronizeStatement(DocumentSynchronizer.java:270)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.updateStatement(DocumentSynchronizer.java:262)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.synchronizeStatements(DocumentSynchronizer.java:193)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.synchronize(DocumentSynchronizer.java:114)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:86)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:20)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```
