### ISSUE TITLE
Wikibase loader does not edit Musical Notation

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#739]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565796017173&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1565796343621-188-1003c1a0-98ff-4458-91ca-716f8d98cafe). It should change the Lilypond notation. However, the value is not changed in Wikidata. There is no error, the value is just not changed.

**Comment by skodapetr** [comment]
As of now this is not implemented in the used library.

**Comment by jakubklimek** [comment]
Now it fails with:
```
com.linkedpipes.etl.executor.api.v1.LpException: Error processing document: https://wikibase.opendata.cz/entity/Q4115189
at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:88)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:19)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [failed-save] The save has failed.
at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:65)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:466)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:406)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:294)
at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.editItemDocument(WikibaseDataEditor.java:315)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.saveDocumentChanges(DocumentSynchronizer.java:364)
at com.linkedpipes.plugin.loader.wikibase.DocumentSynchronizer.synchronize(DocumentSynchronizer.java:117)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:85)
... 9 common frames omitted
```

**Comment by skodapetr** [comment]
@jakubklimek The item and property no longer exist please update the example pipeline.

**Comment by jakubklimek** [comment]
@skodapetr Updated
