### ISSUE TITLE
ClassNotFoundException: javax.xml.bind.annotation.adapters.HexBinaryAdapter

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#754]
```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.HexBinaryAdapter cannot be found by com.linkedpipes.rdf4j-storage-light_3.0.0
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 29 common frames omitted
```

**Comment by skodapetr** [comment]
Where, how ... any details?

**Comment by jakubklimek** [comment]
```
java.io.IOException: context index file /data/lp/etl/working/data/1569405515954-33-f9bfca89-12f5-428d-b7ee-c76b98d62e05/working/working-sesame-15/dataunit-sesame-single/contexts.dat does not exist
at org.eclipse.rdf4j.sail.nativerdf.ContextStore.readContextsFromFile(ContextStore.java:183)
at org.eclipse.rdf4j.sail.nativerdf.ContextStore.<init>(ContextStore.java:102)
at org.eclipse.rdf4j.sail.nativerdf.NativeSailStore.<init>(NativeSailStore.java:95)
at org.eclipse.rdf4j.sail.nativerdf.NativeStore.initializeInternal(NativeStore.java:264)
at org.eclipse.rdf4j.sail.helpers.AbstractSail.init(AbstractSail.java:187)
at org.eclipse.rdf4j.repository.sail.SailRepository.initializeInternal(SailRepository.java:146)
at org.eclipse.rdf4j.repository.base.AbstractRepository.init(AbstractRepository.java:39)
at org.eclipse.rdf4j.repository.base.AbstractRepository.initialize(AbstractRepository.java:31)
at com.linkedpipes.etl.dataunit.core.rdf.RepositoryManager.getGroupRepository(RepositoryManager.java:120)
at com.linkedpipes.etl.dataunit.core.rdf.RepositoryManager.getOrCreateRepository(RepositoryManager.java:104)
at com.linkedpipes.etl.dataunit.core.rdf.RepositoryManager.getRepository(RepositoryManager.java:92)
at com.linkedpipes.etl.dataunit.core.rdf.BaseRdf4jDataUnit.setRepositoryFromManager(BaseRdf4jDataUnit.java:68)
at com.linkedpipes.etl.dataunit.core.rdf.BaseRdf4jDataUnit.initialize(BaseRdf4jDataUnit.java:52)
at com.linkedpipes.etl.dataunit.core.rdf.DefaultSingleGraphDataUnit.initialize(DefaultSingleGraphDataUnit.java:67)
at com.linkedpipes.etl.executor.dataunit.DataUnitContainer.initialize(DataUnitContainer.java:87)
at com.linkedpipes.etl.executor.dataunit.DataUnitManager.onComponentMapByReference(DataUnitManager.java:123)
at com.linkedpipes.etl.executor.component.MapComponent.execute(MapComponent.java:29)
at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponent(PipelineExecutor.java:330)
at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponents(PipelineExecutor.java:303)
at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:95)
at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
2019-09-25 11:58:36,050 [asynchExecutor-1] DEBUG o.e.r.s.n.ContextStore - attempting reconstruction from store (this may take a while)
2019-09-25 11:58:36,050 [asynchExecutor-1] DEBUG o.e.r.s.n.ContextStore - initializing context cache
2019-09-25 11:58:36,050 [asynchExecutor-1] INFO o.e.r.s.n.ContextStore - context index reconstruction complete
2019-09-25 11:58:36,050 [asynchExecutor-1] DEBUG o.e.r.s.n.NativeStore - NativeStore initialized
2019-09-25 11:58:36,050 [asynchExecutor-1] INFO c.l.e.d.c.r.RepositoryManager - Using repository group: single (1) for: https://fit1.opendata.cz/resources/pipelines/1569404778648/4/port/OutputRdf
2019-09-25 11:58:36,054 [asynchExecutor-1] WARN o.e.r.s.h.AbstractSailConnection - Rolling back transaction due to connection close
2019-09-25 11:58:36,054 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecutionFailedOnThrowable
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
```

This happens when I do debug from on [this](https://fit1.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Ffit1.opendata.cz%2Fresources%2Fpipelines%2F1569404778648) pipeline
