### ISSUE TITLE
l-wikibase: Monolingual text update produces "Unknown value"

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#761]
See [this pipeline](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1570177002943), the first row. It updates the statement, but produces "Unknown value" there.

**Comment by skodapetr** [comment]
```psv``` is as a prefix used for expanded values, for a short value (like a monolingual) you need to use ```ps``` prefix.

**Comment by jakubklimek** [comment]
Now [it says](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1565786355863&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1570188606438-471-90f651ae-c0e2-4f08-b5df-0a859110e98f):
```
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
at java.base/java.net.URI$Parser.parse(URI.java:3106)
at java.base/java.net.URI.<init>(URI.java:600)
at java.base/java.net.URI.create(URI.java:881)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.loadPropertyRegister(WikibaseWorker.java:89)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onBeforeExecution(WikibaseWorker.java:64)
at com.linkedpipes.plugin.loader.wikibase.WikibaseLoader.beforeExecution(WikibaseLoader.java:102)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecution.execute(TaskExecution.java:57)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
```

**Comment by skodapetr** [comment]
Missing SPARQL endpoint in configuration.
