### ISSUE TITLE
l-wikibase: unable to load TimeValue

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#765]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1564738794545&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1570189993530-505-64e1580a-bff8-44ae-a48b-cdb44e2896a9).

It says:
```
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Operation failed.
at com.linkedpipes.plugin.loader.wikibase.WikibaseLoader.checkForFailures(WikibaseLoader.java:129)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecution.execute(TaskExecution.java:62)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [modification-failed] Malformed input: +1990-11-01T20:00:00Z
at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:68)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:502)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:442)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:732)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:291)
at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.createItemDocument(WikibaseDataEditor.java:246)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onNew(WikibaseWorker.java:140)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:106)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:28)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
... 1 common frames omitted
```

**Comment by skodapetr** [comment]
Can you create an empty entity with the desired value in wikibase instance?

**Comment by jakubklimek** [comment]
No. - this is the precision issue - precision 11 is days and the time part was not zero.

Nevertheless, when I fixed that, I get a [new error](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1564738794545&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1570193679934-515-28573c94-6e27-4b7f-9997-16959b04d330): 
```
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Operation failed.
at com.linkedpipes.plugin.loader.wikibase.WikibaseLoader.checkForFailures(WikibaseLoader.java:129)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecution.execute(TaskExecution.java:62)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [modification-failed] Statement GUID can not be parsed
at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:68)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:502)
at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:442)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:732)
at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:291)
at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.createItemDocument(WikibaseDataEditor.java:246)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onNew(WikibaseWorker.java:140)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:106)
at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:28)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
... 1 common frames omitted
```
