### ISSUE TITLE
Docker compose deployment fails

### ISSUE THREAD

**Issue by svetlikr** [linkedpipes/etl#777]
Backend services fail when deployed with docker compose (following instructions in Readme) so frontend app can't load data.
With reference to #776, images were built on `openjdk:13-jdk-alpine`.

Executor:

```
20:09:00 [main] INFO  c.l.e.e.Configuration - Reading configuration file: /data/lp/etl/configuration/configuration.properties
!SESSION 2019-11-16 20:09:00.600 -----------------------------------------------
eclipse.buildId=unknown
java.version=13-ea
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY org.eclipse.osgi 4 0 2019-11-16 20:09:00.601
!MESSAGE Error reading configuration: Unable to create lock manager.
!STACK 0
java.io.IOException: Unable to create lock manager.
        at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:698)
        at org.eclipse.osgi.storage.Storage.getChildStorageManager(Storage.java:2011)
        at org.eclipse.osgi.storage.Storage.getInfoInputStream(Storage.java:2028)
        at org.eclipse.osgi.storage.Storage.<init>(Storage.java:216)
        at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:151)
        at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:69)
        at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
        at org.eclipse.osgi.launch.EquinoxFactory.newFramework(EquinoxFactory.java:24)
        at com.linkedpipes.etl.executor.module.ModuleService.start(ModuleService.java:260)
        at com.linkedpipes.etl.executor.module.ModuleService.onApplicationEvent(ModuleService.java:226)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
        at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1364)
        at com.linkedpipes.etl.executor.Executor.startExecutorService(Executor.java:37)
        at com.linkedpipes.etl.executor.Executor.main(Executor.java:41)
20:09:00 [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService
```

Executor monitor:

```
20:07:42 [main] WARN  o.s.c.s.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionFacade' defined in URL [jar:file:/opt/lp/etl/executor-monitor/executor-monitor.jar!/com/linkedpipes/etl/executor/monitor/execution/ExecutionFacade.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionStorage': Invocation of init method failed; nested exception is com.linkedpipes.etl.executor.monitor.MonitorException: Execution working directory does not exists
20:07:42 [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionFacade' defined in URL [jar:file:/opt/lp/etl/executor-monitor/executor-monitor.jar!/com/linkedpipes/etl/executor/monitor/execution/ExecutionFacade.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionStorage': Invocation of init method failed; nested exception is com.linkedpipes.etl.executor.monitor.MonitorException: Execution working directory does not exists
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
        at com.linkedpipes.etl.executor.monitor.ExecutorMonitor.main(ExecutorMonitor.java:102)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionStorage': Invocation of init method failed; nested exception is com.linkedpipes.etl.executor.monitor.MonitorException: Execution working directory does not exists
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1795)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778)
        ... 15 more
Caused by: com.linkedpipes.etl.executor.monitor.MonitorException: Execution working directory does not exists
        at com.linkedpipes.etl.executor.monitor.execution.ExecutionStorage.getExecutionsDirectory(ExecutionStorage.java:77)
        at com.linkedpipes.etl.executor.monitor.execution.ExecutionStorage.onInit(ExecutionStorage.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 28 more
```

**Comment by skodapetr** [comment]
@jakubklimek This needs to be tested for develop and later for master as well (after merge).

**Comment by jakubklimek** [comment]
@skodapetr Tested from develop in Docker for Windows. Can be merged to master.

**Comment by jakubklimek** [comment]
@svetlikr Fixed. Before trying again, please remove all (lp-etl related) containers, images and volumes from docker.
