### ISSUE TITLE
l-wikibase: Key collision

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#779]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1572401813888&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1574083047650-502-130f06ed-aad4-46c9-a6ce-fdd89489f069). In the error report and in the logs, there are errors with exception `Key collision:`. Not sure what it means and what I can do about it.
```
2019-11-18 15:53:50,702 [pool-12-thread-1] ERROR c.l.e.e.a.v.r.DefaultReportWriter - Task (http://www.wikidata.org/entity/Q12034713) failed.
com.linkedpipes.etl.executor.api.v1.LpException: Error processing document: http://www.wikidata.org/entity/Q12034713
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:133)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:29)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.executeTask(TaskExecutor.java:102)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.execute(TaskExecutor.java:86)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskExecutor.run(TaskExecutor.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Key collision: 
	at com.linkedpipes.plugin.loader.wikibase.model.DocumentMerger.statementMap(DocumentMerger.java:297)
	at com.linkedpipes.plugin.loader.wikibase.model.DocumentMerger.mergeStatements(DocumentMerger.java:247)
	at com.linkedpipes.plugin.loader.wikibase.model.DocumentMerger.merge(DocumentMerger.java:146)
	at com.linkedpipes.plugin.loader.wikibase.model.DocumentMerger.<init>(DocumentMerger.java:118)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.onMerge(WikibaseWorker.java:160)
	at com.linkedpipes.plugin.loader.wikibase.WikibaseWorker.accept(WikibaseWorker.java:118)
	... 9 common frames omitted
```

**Comment by skodapetr** [comment]
Caused by two new statements for the same predicate. New statements do not have ID and thus they collided. 

```
<http://www.wikidata.org/entity/Q12034713> <http://www.wikidata.org/prop/P1448> 
    <urn:uuid:671e998b-3ef7-4ea5-adca-01ad7be4341f>,
    <urn:uuid:800eb91b-c4cf-4569-977b-3ac27aafe471>;


<urn:uuid:800eb91b-c4cf-4569-977b-3ac27aafe471> a <http://wikiba.se/ontology#Statement>;
  <http://www.w3.org/ns/prov#wasDerivedFrom> <urn:uuid:a3a5f5cf-5585-47bb-8934-cce1ac3deb25>;
  <http://www.wikidata.org/prop/statement/P1448> "Lípa u Mlýnského rybníka"@cs .

<urn:uuid:a3a5f5cf-5585-47bb-8934-cce1ac3deb25> a <http://wikiba.se/ontology#Reference>;
  <http://www.wikidata.org/prop/reference/P248> <http://www.wikidata.org/entity/Q26778346> .



<urn:uuid:671e998b-3ef7-4ea5-adca-01ad7be4341f> a <http://wikiba.se/ontology#Statement>;
  <http://www.w3.org/ns/prov#wasDerivedFrom> <urn:uuid:e5f12191-6539-405a-8c73-c593ebca750d>;
  <http://www.wikidata.org/prop/statement/P1448> "Lípa u Mlýnského rybníka"@cs .

<urn:uuid:e5f12191-6539-405a-8c73-c593ebca750d> a <http://wikiba.se/ontology#Reference>;
  <http://www.wikidata.org/prop/reference/P248> <http://www.wikidata.org/entity/Q26778346> .

`
``` 

Now two statements should be created in wikibase.
