### ISSUE TITLE
SPARQL Endpoint gives "label too long"

### ISSUE THREAD

**Issue by bencomp** [linkedpipes/etl#790]
When I try to use the <https://api.data.netwerkdigitaalerfgoed.nl/datasets/hackalod/RM-PublicDomainImages/services/RM-PublicDomainImages/sparql> SPARQL endpoint in a pipeline, the component fails with

```
2019-12-05 13:18:23,002 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://demo.etl.linkedpipes.com/resources/pipelines/1575540691693/component/7a26-b039
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: java.lang.IllegalArgumentException: The label in the input is too long
	at java.base/java.net.IDN.toASCIIInternal(IDN.java:340)
	at java.base/java.net.IDN.toASCII(IDN.java:122)
	at java.base/java.net.IDN.toASCII(IDN.java:151)
	at com.linkedpipes.plugin.extractor.sparql.endpoint.SparqlEndpoint.getEndpoint(SparqlEndpoint.java:113)
	at com.linkedpipes.plugin.extractor.sparql.endpoint.SparqlEndpoint.createRepository(SparqlEndpoint.java:93)
	at com.linkedpipes.plugin.extractor.sparql.endpoint.SparqlEndpoint.execute(SparqlEndpoint.java:69)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
```

It looks like the code at
https://github.com/linkedpipes/etl/blob/4c683525e861ebdc20715742c46533b0b7147a53/plugins/e-sparqlEndpoint/src/main/java/com/linkedpipes/plugin/extractor/sparql/endpoint/SparqlEndpoint.java#L111-L114

tries to convert the whole endpoint URI except the scheme to ASCII, which is unacceptable to the internal Java IDN conversion. Could it be that this is too much (i.e. because the input is longer than 63 characters), and that only the actual domain name should be converted?

**Comment by jakubklimek** [comment]
[Works now](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1575638441011&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1575638462681-688-513fe2a4-fe49-4e55-95c7-eee7d85cb5fa)

**Comment by bencomp** [comment]
Awesome! Thanks for the quick response!
