### ISSUE TITLE
NPE in SPARQL construct to file list

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#793]
NPE in SPARQL construct to file list in [this execution](https://fit2.opendata.cz/#/pipelines/edit/canvas?pipeline=https://fit2.opendata.cz/resources/pipelines/created-1491043403748&execution=https://fit2.opendata.cz/resources/executions/1578985029956-29-86cfb864-8425-4dce-b28c-57870976a6ce): 
```
2020-01-14 08:56:50,108 [SPARQL construct to file list] INFO  c.l.p.t.s.c.SparqlConstructToFileList - Executing query:

PREFIX adhoc: <http://linked.opendata.cz/ontology/adhoc/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
CONSTRUCT { 
?subject a ?sourceClass ;
   ?property ?object .
?object a ?targetClass .
} 
WHERE { 
?desc adhoc:endpointUri "http://webenemasuno.linkeddata.es/sparql" ;
   adhoc:sourceClass ?sourceClass ;
   adhoc:property ?property .
OPTIONAL { ?desc adhoc:targetClass ?targetClass .  }
FILTER(?property != rdf:type)
BIND(IF(BOUND(?targetClass), IRI(CONCAT(STR(?targetClass), "/instance")), "") as ?object )
BIND(IRI(CONCAT(STR(?sourceClass), "/instance")) as ?subject)
 } 

2020-01-14 08:56:50,143 [SPARQL construct to file list] INFO  c.l.e.e.a.v.s.DefaultProgressReport - Progress report 60/129
2020-01-14 08:56:50,153 [SPARQL construct to file list] INFO  c.l.e.e.e.ExecutionObserver - onComponentUserCodeFailed : https://fit2.opendata.cz/resources/pipelines/created-1491043403748/components/e82d7213-6f94-4781-973a-0b9cae14aed6
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser - onComponentExecuted
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser - Close data units:
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED ts/e82d7213-6f94-4781-973a-0b9cae14aed6/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/17/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED ts/9c1430fd-4044-4d1c-a6de-a129e569437e/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/24/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED ts/8490edc3-0cc2-4b69-b828-a75ec795fb07/port/OutputRdf : OutputRdf
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED ts/e82d7213-6f94-4781-973a-0b9cae14aed6/port/Tasks : Tasks
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/14/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/22/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED ts/e82d7213-6f94-4781-973a-0b9cae14aed6/port/InputRdf : InputRdf
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/23/port/OutputRdf : OutputRdf
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED ts/67c6f87f-08f6-4243-ac42-6605a350abf5/port/OutputRdf : OutputRdf
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED ts/2cf2db35-ec48-4d1b-8161-8336bfd7bfe7/port/OutputRdf : OutputRdf
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED ts/e82d7213-6f94-4781-973a-0b9cae14aed6/port/Configuration : Configuration
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/25/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/19/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,342 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED fit2.opendata.cz/resources/pipelines/created-1491043403748/26/port/OutputFiles : OutputFiles
2020-01-14 08:57:57,343 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (7)
2020-01-14 08:57:57,343 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-01-14 08:57:57,343 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (6)
2020-01-14 08:57:57,343 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-01-14 08:57:57,343 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (5)
2020-01-14 08:57:57,343 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-01-14 08:57:57,343 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (4)
2020-01-14 08:57:57,343 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-01-14 08:57:57,344 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://fit2.opendata.cz/resources/pipelines/created-1491043403748/components/e82d7213-6f94-4781-973a-0b9cae14aed6
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.File.<init>(File.java:359)
	at com.linkedpipes.etl.dataunit.core.files.DefaultFilesDataUnit.createFile(DefaultFilesDataUnit.java:48)
	at com.linkedpipes.plugin.transformer.sparql.constructtofilelist.SparqlConstructToFileList.executeTaskGroups(SparqlConstructToFileList.java:118)
	at com.linkedpipes.plugin.transformer.sparql.constructtofilelist.SparqlConstructToFileList.execute(SparqlConstructToFileList.java:80)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
```

**Comment by skodapetr** [comment]
There is missing file name in the task definition:
```
<urn:uuid:76a7a2c9-595d-44ae-9a4a-b500c885c96c> a <http://plugins.linkedpipes.com/ontology/t-sparqlConstructToFileList#Task>;
  <http://plugins.linkedpipes.com/ontology/t-sparqlConstructToFileList#fileFormat> "text/turtle";
  <http://plugins.linkedpipes.com/ontology/t-sparqlConstructToFileList#hasTaskQuery>
    <urn:uuid:b12094f2-6573-4a38-a35d-ee543d47a1ad> .

```
