### ISSUE TITLE
Input files for transformation components

### ISSUE THREAD

**Issue by versant2612** [linkedpipes/etl#799]
How can I specify the input file name and location to "Tabular to RDF" component? 
The input file is on the same machine where the linkedpipes is installed, in this casa do I need an Extractor?

**Comment by jakubklimek** [comment]
@versant2612 Please see the [tutorial on how to convert tabular data to RDF](https://etl.linkedpipes.com/tutorials/csv-to-rdf/) first.

If your CSV file is on your local file system, then you need the [files from local extractor](https://etl.linkedpipes.com/components/e-filesfromlocal). This one needs to be [unbanned in the configuration file](https://github.com/linkedpipes/etl/blob/master/deploy/configuration.properties.sample#L46) as it is disabled by default due to security concerns on web instances.

**Comment by versant2612** [comment]
I changed the configuration files, commenting out these lines and restarted the executor, but I'm still getting the error message about the banned component

cloud-di@vm029:~/etl/deploy$ grep executor.banned_jar_iri_patterns conf*
configuration.docker.properties:**#** executor.banned_jar_iri_patterns = ".*e-filesFromLocal.*",".*l-filesToLocal.*",".*x-deleteDirectory.*"
configuration.properties:**#** executor.banned_jar_iri_patterns = ".*e-filesFromLocal.*",".*l-filesToLocal.*",".*x-deleteDirectory.*"
configuration.properties.sample:**#** executor.banned_jar_iri_patterns = ".*e-filesFromLocal.*",".*l-filesToLocal.*",".*x-deleteDirectory.*"

Error messages

cloud-di@vm029:~/etl/deploy$ tail -30 executor.log
        at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:93)
        at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
**15:14:30 [asynchExecutor-1] ERROR c.l.e.e.p.PipelineExecutor - Banned component.
com.linkedpipes.etl.executor.module.BannedComponent: Required component: http://etl.linkedpipes.com/resources/jars/l-filesToLocal/0.0.0 is banned by: .*l-filesToLocal.***
        at com.linkedpipes.etl.executor.module.ModuleService.checkIfBundleIsAllowed(ModuleService.java:199)
        at com.linkedpipes.etl.executor.module.ModuleService.getComponent(ModuleService.java:137)
        at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.loadComponents(PipelineExecutor.java:280)
        at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.initialize(PipelineExecutor.java:160)
        at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:93)
        at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jakubklimek** [comment]
@versant2612 This is weird. I just tested it and it worked for me with the line commented out in `configuration.properties`. Can you try restarting all 4 parts, just to be sure?

**Comment by versant2612** [comment]
The virtual machine was restarted by cloud administrator for others reasons. 
I started all 4 parts and it is working now. 
Thanks!

I have another error message with File to Local component. Should I open another issue?

**Comment by jakubklimek** [comment]
Yes please

**Comment by versant2612** [comment]
OK @jakubklimek , I will. 
I still have a doubt about "_Path to a local file or directory_" parameter of "_Files from local_" component. Can I specify a directory path and a regular expression like "*.xml" to select a list of files?

**Comment by jakubklimek** [comment]
@versant2612 you can only specify a single file or a single directory (which can include subdirectories). This will be available in the pipeline as a whole. You can then use Files filter with a regular expression.

**Comment by versant2612** [comment]
Thank you. 
I included Files filter in my pipelines.
