### ISSUE TITLE
JSON-LD stopped loading after recent upgrade

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#816]
After upgrade from 0d31ae5e8900927be65e2fd402b1f6f78140f312 to c05135bd618d6f09dc6f17433f7e746d4529f805, Files to RDF (single graph) stopped transforming JSON-LD with the following error:
```
2020-07-24 12:18:13,817 [Files to RDF] INFO  c.l.e.e.a.v.s.DefaultProgressReport - Progress report start 0/1
2020-07-24 12:18:13,818 [Files to RDF] INFO  c.l.e.e.e.ExecutionObserver - onComponentUserCodeFailed : https://demo.etl.linkedpipes.com/resources/pipelines/1595585201339/5
2020-07-24 12:18:13,820 [asynchExecutor-1] ERROR c.l.e.e.c.ExecuteComponent - Can't save data unit after component failed.
com.linkedpipes.etl.executor.ExecutorException: Can't save data unit: https://demo.etl.linkedpipes.com/resources/pipelines/1595585201339/5/port/OutputRdf
	at com.linkedpipes.etl.executor.dataunit.DataUnitContainer.save(DataUnitContainer.java:124)
	at com.linkedpipes.etl.executor.dataunit.DataUnitManager.onComponentDidExecute(DataUnitManager.java:106)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.execute(ExecuteComponent.java:81)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponent(PipelineExecutor.java:334)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponents(PipelineExecutor.java:307)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:95)
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't execute repository procedure.
	at com.linkedpipes.etl.dataunit.core.rdf.ActionExecutor.execute(ActionExecutor.java:24)
	at com.linkedpipes.etl.dataunit.core.rdf.BaseRdf4jDataUnit.execute(BaseRdf4jDataUnit.java:37)
	at com.linkedpipes.etl.dataunit.core.rdf.DefaultGraphListDataUnit.saveContent(DefaultGraphListDataUnit.java:96)
	at com.linkedpipes.etl.dataunit.core.rdf.DefaultGraphListDataUnit.save(DefaultGraphListDataUnit.java:70)
	at com.linkedpipes.etl.executor.dataunit.DataUnitContainer.save(DataUnitContainer.java:121)
	... 9 common frames omitted
Caused by: org.eclipse.rdf4j.rio.UnsupportedRDFormatException: Did not recognise RDF format object TriG (mimeTypes=application/trig, application/x-trig; ext=trig)
	at org.eclipse.rdf4j.rio.Rio.lambda$unsupportedFormat$0(Rio.java:566)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at org.eclipse.rdf4j.rio.Rio.createWriter(Rio.java:127)
	at com.linkedpipes.etl.dataunit.core.rdf.DefaultGraphListDataUnit.lambda$saveContent$0(DefaultGraphListDataUnit.java:98)
	at com.linkedpipes.etl.dataunit.core.rdf.ActionExecutor.execute(ActionExecutor.java:19)
	... 13 common frames omitted
2020-07-24 12:18:13,821 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://demo.etl.linkedpipes.com/resources/pipelines/1595585201339/5
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't determine format for file: role.jsonld
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.transformer.filesToRdf.FilesToRdf.getFormat(FilesToRdf.java:107)
	at com.linkedpipes.plugin.transformer.filesToRdf.FilesToRdf.loadEntry(FilesToRdf.java:92)
	at com.linkedpipes.plugin.transformer.filesToRdf.FilesToRdf.loadFiles(FilesToRdf.java:78)
	at com.linkedpipes.plugin.transformer.filesToRdf.FilesToRdf.execute(FilesToRdf.java:51)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
```

See [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1595585201339&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1595585893692-939-3f500124-bedb-41df-af84-df75f5a306c9)

And [this one on older instance](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1595586085275&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1595586088803-665-fa6a3fc5-153b-416f-8bb4-65d44c77aae6)

**Comment by jakubklimek** [comment]
The same problem also manifested itself with Files to RDF single graph with "format" set to JSON-LD explicitly:
```
2020-07-24 14:36:39,153 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-07-24 14:36:39,154 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://etl.data-mff.opendata.cz/resources/pipelines/1595591831244/11
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't determine format for file: číselník-platových-tříd.jsonld
at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.getFormat(FilesToRdfGraph.java:99)
at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.loadEntry(FilesToRdfGraph.java:84)
at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.loadFiles(FilesToRdfGraph.java:77)
at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.execute(FilesToRdfGraph.java:52)
at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
```

**Comment by skodapetr** [comment]
This was caused by the commit where I fixed the parent pom of the rdf4j-storage-light, this reveal another issue that was cause of this. As a part of solving this issue I've also updated rdf4j library from 3.0.0 to 3.2.3.
