### ISSUE TITLE
Union causes java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#817]
See [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1596020201388&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1596022911750-956-a1e6497e-cad3-4dd9-bad7-501466e8957e)

**Comment by skodapetr** [comment]
Log file content
```
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser - onComponentExecuted
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser - Close data units:
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/e666-8ae6/port/OutputRdf : OutputRdf
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED t/432c-85fb/port/OutputRdf : OutputRdf
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -   CLOSE SAVED demo.etl.linkedpipes.com/resources/pipelines/1596020201388/16/port/InputRdf : InputRdf
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.e.d.DataUnitCloser -         SAVED demo.etl.linkedpipes.com/resources/pipelines/1596020201388/16/port/OutputRdf : OutputRdf
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (4)
2020-07-29 13:41:54,377 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (3)
2020-07-29 13:41:54,377 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-07-29 13:41:54,377 [asynchExecutor-1] INFO  c.l.e.d.c.r.RepositoryManager - Request to close repository group: single (2)
2020-07-29 13:41:54,377 [asynchExecutor-1] ERROR c.l.e.d.c.r.RepositoryManager - Manager was asked to close unmanaged repository.
2020-07-29 13:41:54,378 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://demo.etl.linkedpipes.com/resources/pipelines/1596020201388/16
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't execute repository procedure.
	at com.linkedpipes.etl.dataunit.core.rdf.ActionExecutor.execute(ActionExecutor.java:24)
	at com.linkedpipes.etl.dataunit.core.rdf.BaseRdf4jDataUnit.execute(BaseRdf4jDataUnit.java:37)
	at com.linkedpipes.plugin.transformer.singleGraphUnion.SingleGraphUnion.lambda$execute$1(SingleGraphUnion.java:22)
	at com.linkedpipes.etl.dataunit.core.rdf.ActionExecutor.execute(ActionExecutor.java:19)
	at com.linkedpipes.etl.dataunit.core.rdf.BaseRdf4jDataUnit.execute(BaseRdf4jDataUnit.java:37)
	at com.linkedpipes.plugin.transformer.singleGraphUnion.SingleGraphUnion.execute(SingleGraphUnion.java:21)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
Caused by: java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
	at org.eclipse.rdf4j.common.iteration.CloseableIteratorIteration.next(CloseableIteratorIteration.java:71)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.next(IterationWrapper.java:84)
	at org.eclipse.rdf4j.sail.base.SailClosingIteration.next(SailClosingIteration.java:94)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.next(IterationWrapper.java:84)
	at org.eclipse.rdf4j.common.iteration.ExceptionConvertingIteration.next(ExceptionConvertingIteration.java:86)
	at org.eclipse.rdf4j.repository.RepositoryResult.next(RepositoryResult.java:58)
	at com.linkedpipes.plugin.transformer.singleGraphUnion.SingleGraphUnion.addNamespaces(SingleGraphUnion.java:35)
	at com.linkedpipes.plugin.transformer.singleGraphUnion.SingleGraphUnion.lambda$execute$0(SingleGraphUnion.java:23)
	at com.linkedpipes.etl.dataunit.core.rdf.ActionExecutor.execute(ActionExecutor.java:19)
	... 9 common frames omitted
```

**Comment by jakubklimek** [comment]
Without the union (when I connect its inputs to the targets of its outputs) the pipeline works fine
