### ISSUE TITLE
add support for Apache Jena Fuseki to Graph store purger

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#826]
Currently, using Graph Store Purger with Apache Jena Fuseki results in Bad Request.
e.g. http://localhost:3030/nkod/data endpoint.

See [this execution](https://dev.nkod.opendata.cz/etl/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdev.nkod.opendata.cz%2Fetl%2Fresources%2Fpipelines%2F1599204253251&execution=https:%2F%2Fdev.nkod.opendata.cz%2Fetl%2Fresources%2Fexecutions%2F1599204310512-28-748f0d12-e0ec-4f0f-a5e8-20ebf0f926cb)

```
2020-09-04 09:21:53,093 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://dev.nkod.opendata.cz/etl/resources/pipelines/1582707975888/component/1d37-bd64
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Delete request failed on: http://localhost:3030/nkod/data?graph-uri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2FMinFinCZ%2F9999994%2F22d3e33bf58ff332ad1b2e714c1fc716
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.deleteGraph(GraphStorePurger.java:153)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.purgeEndpoint(GraphStorePurger.java:85)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.execute(GraphStorePurger.java:60)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Invalid response: Bad Request
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.checkResponse(GraphStorePurger.java:186)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.executeHttpRequest(GraphStorePurger.java:163)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.deleteGraph(GraphStorePurger.java:151)
	... 6 common frames omitted
```

**Comment by namedgraph** [comment]
Isn't the GSP query param `graph` instead of `graph-uri`?
https://www.w3.org/TR/2013/REC-sparql11-http-rdf-update-20130321/#indirect-graph-identification
