### ISSUE TITLE
Pipeline migration errors after recent update

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#862]
in storage.log:
```
2021-06-07 07:38:44,427 [main] ERROR c.linkedpipes.etl.storage.pipeline.PipelineStorage - Can't load pipeline: /data/lp/etl/storage/pipelines/created-1497274306558.trig
org.eclipse.rdf4j.rio.RDFParseException: Unexpected character U+7B at index 44: http://data.openbudgets.eu/resource/dataset/{{@@continent@@}}/{{@@country@@}}/{{@@division_level@@}}/{{@@organization@@}}/{{@@year@@}}/budget/{{@@operation_character@@}} [line 603]
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:272)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:651)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportError(TurtleParser.java:1294)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:417)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:405)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:937)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:569)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:451)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:373)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:368)
        at org.eclipse.rdf4j.rio.trig.TriGParser.parseTriples(TriGParser.java:233)
        at org.eclipse.rdf4j.rio.trig.TriGParser.parseGraph(TriGParser.java:160)
        at org.eclipse.rdf4j.rio.trig.TriGParser.parseStatement(TriGParser.java:112)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:162)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:125)
        at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:253)
        at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:235)
        at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:226)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.loadFromFile(PipelineLoader.java:49)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.load(PipelineLoader.java:40)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipeline(PipelineStorage.java:90)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipelines(PipelineStorage.java:73)
        at com.linkedpipes.etl.storage.pipeline.PipelineManager.initialize(PipelineManager.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
        at com.linkedpipes.etl.storage.Storage.main(Storage.java:101)
2021-06-07 07:38:46,199 [main] INFO  c.l.etl.storage.pipeline.transformation.Migration - Migrating pipeline 'https://demo.etl.linkedpipes.com/resources/pipelines/created-1463739525964' version '1'
2021-06-07 07:38:46,209 [main] ERROR c.linkedpipes.etl.storage.pipeline.PipelineStorage - Can't load pipeline: /data/lp/etl/storage/pipelines/created-1463739525964.trig
java.lang.RuntimeException: Missing template: http://opendata.cz/resource/lp/etl/components/e-portal-gov-cz/0.0.0
        at com.linkedpipes.etl.storage.migration.MigrateV1ToV2.getCoreTemplate(MigrateV1ToV2.java:127)
        at com.linkedpipes.etl.storage.migration.MigrateV1ToV2.migrateComponent(MigrateV1ToV2.java:108)
        at com.linkedpipes.etl.storage.migration.MigrateV1ToV2.pipeline(MigrateV1ToV2.java:101)
        at com.linkedpipes.etl.storage.pipeline.transformation.Migration.v1Tov2(Migration.java:112)
        at com.linkedpipes.etl.storage.pipeline.transformation.Migration.migrate(Migration.java:66)
        at com.linkedpipes.etl.storage.pipeline.transformation.TransformationFacade.migrateThrowOnWarning(TransformationFacade.java:37)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.migratePipeline(PipelineLoader.java:64)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.load(PipelineLoader.java:42)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipeline(PipelineStorage.java:90)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipelines(PipelineStorage.java:73)
        at com.linkedpipes.etl.storage.pipeline.PipelineManager.initialize(PipelineManager.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
        at com.linkedpipes.etl.storage.Storage.main(Storage.java:101)

```

**Comment by skodapetr** [comment]
This should not be connected to the recent update, it just mean that are some invalid pipelines that are ignored. Please check the log for before the update.

**Comment by jakubklimek** [comment]
OK, it is not connected to the update. Nevertheless, why are the pipelines invalid? Shouldn't this be handled?
```
org.eclipse.rdf4j.rio.RDFParseException: Unexpected character U+7B at index 44: http://data.openbudgets.eu/resource/dataset/{{@@continent@@}}/{{@@country@@}}/{{@@division_level@@}}/{{@@organization@@}}/{{@@year@@}}/budget/{{@@operation_character@@}} [line 603]
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:272)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:651)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportError(TurtleParser.java:1282)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:417)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:405)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:925)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:557)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:439)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:367)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:362)
        at org.eclipse.rdf4j.rio.trig.TriGParser.parseTriples(TriGParser.java:233)
        at org.eclipse.rdf4j.rio.trig.TriGParser.parseGraph(TriGParser.java:160)
        at org.eclipse.rdf4j.rio.trig.TriGParser.parseStatement(TriGParser.java:112)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:156)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:119)
        at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:253)
        at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:235)
        at com.linkedpipes.etl.storage.rdf.RdfUtils.read(RdfUtils.java:226)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.loadFromFile(PipelineLoader.java:49)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.load(PipelineLoader.java:40)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipeline(PipelineStorage.java:90)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipelines(PipelineStorage.java:73)
        at com.linkedpipes.etl.storage.pipeline.PipelineManager.initialize(PipelineManager.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
        at com.linkedpipes.etl.storage.Storage.main(Storage.java:101)
2021-06-09 12:19:00,274 [main] INFO  c.l.etl.storage.pipeline.transformation.Migration - Migrating pipeline 'https://demo.etl.linkedpipes.com/resources/pipelines/created-1463739525964' version '1'
2021-06-09 12:19:00,276 [main] ERROR c.linkedpipes.etl.storage.pipeline.PipelineStorage - Can't load pipeline: /data/lp/etl/storage/pipelines/created-1463739525964.trig
java.lang.RuntimeException: Missing template: http://opendata.cz/resource/lp/etl/components/e-portal-gov-cz/0.0.0
        at com.linkedpipes.etl.storage.migration.MigrateV1ToV2.getCoreTemplate(MigrateV1ToV2.java:127)
        at com.linkedpipes.etl.storage.migration.MigrateV1ToV2.migrateComponent(MigrateV1ToV2.java:108)
        at com.linkedpipes.etl.storage.migration.MigrateV1ToV2.pipeline(MigrateV1ToV2.java:101)
        at com.linkedpipes.etl.storage.pipeline.transformation.Migration.v1Tov2(Migration.java:112)
        at com.linkedpipes.etl.storage.pipeline.transformation.Migration.migrate(Migration.java:66)
        at com.linkedpipes.etl.storage.pipeline.transformation.TransformationFacade.migrateThrowOnWarning(TransformationFacade.java:37)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.migratePipeline(PipelineLoader.java:64)
        at com.linkedpipes.etl.storage.pipeline.PipelineLoader.load(PipelineLoader.java:42)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipeline(PipelineStorage.java:90)
        at com.linkedpipes.etl.storage.pipeline.PipelineStorage.loadPipelines(PipelineStorage.java:73)
        at com.linkedpipes.etl.storage.pipeline.PipelineManager.initialize(PipelineManager.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
        at com.linkedpipes.etl.storage.Storage.main(Storage.java:101)
2021-06-09 12:19:01,487 [main] INFO  com.linkedpipes.etl.storage.web.WebServer - Starting server on port: 8083
2021-06-09 12:19:01,511 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @5966ms to org.eclipse.jetty.util.log.Slf4jLog
2021-06-09 12:19:01,590 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 15.0.3+3-Ubuntu-1
2021-06-09 12:19:01,610 [main] INFO  o.eclipse.jetty.server.handler.ContextHandler.ROOT - Initializing Spring root WebApplicationContext
2021-06-09 12:19:01,610 [main] INFO  org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
2021-06-09 12:19:01,962 [main] INFO  org.springframework.web.context.ContextLoader - Root WebApplicationContext initialized in 352 ms
2021-06-09 12:19:01,966 [main] INFO  o.eclipse.jetty.server.handler.ContextHandler.ROOT - Initializing Spring DispatcherServlet 'org.springframework.web.servlet.DispatcherServlet-6107165'
2021-06-09 12:19:01,966 [main] INFO  org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'org.springframework.web.servlet.DispatcherServlet-6107165'
2021-06-09 12:19:01,974 [main] INFO  org.springframework.web.servlet.DispatcherServlet - Completed initialization in 8 ms
2021-06-09 12:19:01,975 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@67531e3a{/,jar:file:/opt/lp/etl/deploy/storage/storage.jar!/web/,AVAILABLE}
2021-06-09 12:19:01,987 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@61d34b4{HTTP/1.1,[http/1.1]}{0.0.0.0:8083}
2021-06-09 12:19:01,988 [main] INFO  org.eclipse.jetty.server.Server - Started @6443ms

```

**Comment by skodapetr** [comment]
@jakubklimek  If you have any idea how, you can create a new issue. The first case if missing template, so the older version of pipeline can not be migrated. The second one is invalid UTF-8 character.

**Comment by jakubklimek** [comment]
OK. so probably related to #544 .
