### ISSUE TITLE
Union: No such element: null

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#865]
See [this execution](https://dev.nkod.opendata.cz/etl/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdev.nkod.opendata.cz%2Fetl%2Fresources%2Fpipelines%2F1611038931779&execution=https:%2F%2Fdev.nkod.opendata.cz%2Fetl%2Fresources%2Fexecutions%2F1623304569853-174-03f10027-df84-4244-a7c0-47bb704278bb). After update, Union is not working and ends with:
```
2021-06-10 07:58:08,033 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://dev.nkod.opendata.cz/etl/resources/pipelines/1611038931779/13
com.linkedpipes.etl.executor.ExecutorException: Can't merge data.
	at com.linkedpipes.etl.executor.component.configuration.Configuration.prepareConfiguration(Configuration.java:98)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.configureComponent(ExecuteComponent.java:176)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.initialize(ExecuteComponent.java:114)
	at com.linkedpipes.etl.executor.component.ExecuteComponent.execute(ExecuteComponent.java:75)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponent(PipelineExecutor.java:334)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.executeComponents(PipelineExecutor.java:307)
	at com.linkedpipes.etl.executor.pipeline.PipelineExecutor.execute(PipelineExecutor.java:95)
	at com.linkedpipes.etl.executor.web.servlet.ExecutionServlet.lambda$execute$0(ExecutionServlet.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: com.linkedpipes.etl.rdf.utils.RdfUtilsException: Can't execute query.
	at com.linkedpipes.etl.rdf.utils.rdf4j.Rdf4jSource.sparqlSelect(Rdf4jSource.java:57)
	at com.linkedpipes.etl.rdf.utils.RdfUtils.sparqlSelect(RdfUtils.java:185)
	at com.linkedpipes.etl.executor.component.configuration.DefaultControl.loadControl(DefaultControl.java:266)
	at com.linkedpipes.etl.executor.component.configuration.DefaultControl.loadControlInferDefaults(DefaultControl.java:230)
	at com.linkedpipes.etl.executor.component.configuration.DefaultControl.init(DefaultControl.java:89)
	at com.linkedpipes.etl.executor.rdf.entity.EntityMerger.merge(EntityMerger.java:52)
	at com.linkedpipes.etl.executor.component.configuration.Configuration.prepareConfiguration(Configuration.java:96)
	... 10 common frames omitted
Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:970)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.BindingSetAssignmentInliner$BindingSetAssignmentVisitor.meet(BindingSetAssignmentInliner.java:46)
	at org.eclipse.rdf4j.query.algebra.BindingSetAssignment.visit(BindingSetAssignment.java:49)
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:104)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:572)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.BindingSetAssignmentInliner$BindingSetAssignmentVisitor.meetNode(BindingSetAssignmentInliner.java:82)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetBinaryTupleOperator(AbstractQueryModelVisitor.java:531)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:305)
	at org.eclipse.rdf4j.query.algebra.Join.visit(Join.java:65)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.Projection.visitChildren(Projection.java:81)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:572)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.BindingSetAssignmentInliner$BindingSetAssignmentVisitor.meetNode(BindingSetAssignmentInliner.java:82)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetUnaryTupleOperator(AbstractQueryModelVisitor.java:592)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:400)
	at org.eclipse.rdf4j.query.algebra.Projection.visit(Projection.java:75)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:572)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.BindingSetAssignmentInliner$BindingSetAssignmentVisitor.meetNode(BindingSetAssignmentInliner.java:82)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:415)
	at org.eclipse.rdf4j.query.algebra.QueryRoot.visit(QueryRoot.java:45)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.BindingSetAssignmentInliner.optimize(BindingSetAssignmentInliner.java:36)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.optimize(StrictEvaluationStrategy.java:272)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.evaluateInternal(SailSourceConnection.java:244)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.evaluate(AbstractSailConnection.java:249)
	at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:50)
	at com.linkedpipes.etl.rdf.utils.rdf4j.Rdf4jSource.sparqlSelect(Rdf4jSource.java:51)
	... 16 common frames omitted
```

**Comment by bencomp** [comment]
I'm running into the same issue in the *Graph merger* component in my [Europeana SHACL test pipeline execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https%3A%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1622734552419&execution=https%3A%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1623314049889-1608-b32cfa0a-9984-4f3e-a2c8-19c916b1b022). It looks like when I skip badly formatted files in the *Files to RDF* component, the list of graphs in `graphs.json` is longer than the number of graphs found in `data.trig`.

This behaviour must have changed in the past week, as the same pipeline worked fine about a week ago.

**Comment by skodapetr** [comment]
The issues is connected to the components without the configuration. During the configuration preparation a SPARQL select query is asked, this query contains ```VALUES``` section. For components without configuration this values list is empty, that cause rdf4j to crash.
