### ISSUE TITLE
Graph store purger does not work with GraphDB

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#923]
See [this execution](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2F1649829726340&execution=https:%2F%2Fetl.opendata.cz%2Fresources%2Fexecutions%2F1651558697864-862-6fc0fddf-b129-4e6d-8921-35c359aa494b). In the log, there is:
```
2022-05-03 08:19:03,731 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://etl.opendata.cz/resources/pipelines/1649829726340/component/5b78-b371
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Delete request failed on: http://localhost:7200/repositories/nkod/rdf-graphs/service?graph-uri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00297313%2F995215483
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.deleteGraph(GraphStorePurger.java:153)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.purgeEndpoint(GraphStorePurger.java:85)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.execute(GraphStorePurger.java:60)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
	... 2 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Invalid response: 
	at com.linkedpipes.etl.executor.api.v1.service.DefaultExceptionFactory.failure(DefaultExceptionFactory.java:12)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.checkResponse(GraphStorePurger.java:186)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.executeHttpRequest(GraphStorePurger.java:163)
	at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.deleteGraph(GraphStorePurger.java:151)
	... 6 common frames omitted
```

Using curl I get:
```bash
klimek@xrg21:~$ curl -v -X DELETE http://localhost:7200/repositories/nkod/rdf-graphs/service?graph-uri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00297313%2F995215483
*   Trying 127.0.0.1:7200...
* Connected to localhost (127.0.0.1) port 7200 (#0)
> DELETE /repositories/nkod/rdf-graphs/service?graph-uri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00297313%2F995215483 HTTP/1.1
> Host: localhost:7200
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400
< Vary: Accept-Encoding
< Cache-Control: no-store
< Content-Type: text/plain;charset=UTF-8
< Content-Language: en-US
< Content-Length: 63
< Date: Tue, 03 May 2022 06:23:33 GMT
< Connection: close
< Server: GraphDB-Free/9.10.3 RDF4J/3.7.3
<
* Closing connection 0
Named or default graph expected for indirect reference request.
```

According to the [documentation](https://graphdb.ontotext.com/documentation/free/sparql-compliance.html#supported-parameters-for-requests-on-indirectly-referenced-named-graphs) the graph IRI is expected in a `graph` parameter, not `graph-uri` as for Virtuoso.

I suggest adding a configuration option for specifying the param name, defaulting to `graph` per [specification](https://www.w3.org/TR/sparql11-http-rdf-update/#http-delete).

**Comment by jakubklimek** [comment]
Now, I get:
```
2022-05-11 07:53:21,560 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://sk-nkod.opendata.cz/etl/resources/pipelines/1651823993742/component/fa93-854e
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: java.lang.IllegalArgumentException: Entity may not be null
at org.apache.http.util.Args.notNull(Args.java:54)
at org.apache.http.util.EntityUtils.toString(EntityUtils.java:307)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.checkResponse(GraphStorePurger.java:190)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.executeHttpRequest(GraphStorePurger.java:181)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.executeHttpDelete(GraphStorePurger.java:162)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.deleteGraphGraphDB(GraphStorePurger.java:155)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.deleteGraph(GraphStorePurger.java:145)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.purgeEndpoint(GraphStorePurger.java:86)
at com.linkedpipes.plugin.exec.graphstorepurger.GraphStorePurger.execute(GraphStorePurger.java:61)
at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
```
