### ISSUE TITLE
SPARQL Endpoint loader does not work with GraphDB

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#927]
I get
```
2022-05-11 13:27:32,955 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://sk-nkod.opendata.cz/etl/resources/pipelines/1651823993742/component/e345-8323
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: org.eclipse.rdf4j.query.UpdateExecutionException: Missing parameter: query
at org.eclipse.rdf4j.repository.sparql.query.SPARQLUpdate.execute(SPARQLUpdate.java:47)
at com.linkedpipes.plugin.loader.sparql.endpoint.SparqlEndpointLoader.clearGraph(SparqlEndpointLoader.java:112)
at com.linkedpipes.plugin.loader.sparql.endpoint.SparqlEndpointLoader.clearGraph(SparqlEndpointLoader.java:68)
at com.linkedpipes.plugin.loader.sparql.endpoint.SparqlEndpointLoader.execute(SparqlEndpointLoader.java:56)
at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
Caused by: org.eclipse.rdf4j.repository.RepositoryException: Missing parameter: query
at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1064)
at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeNoContent(SPARQLProtocolSession.java:1018)
at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendUpdate(SPARQLProtocolSession.java:386)
at org.eclipse.rdf4j.repository.sparql.query.SPARQLUpdate.execute(SPARQLUpdate.java:41)
... 7 common frames omitted
```

**Comment by skodapetr** [comment]
We employ rdf4j to execute CLEAR GRAPH query, this call produce the warning. We may need to explore compatibility between rdf4j and GraphDB. Alternative is to provide a custom HTTP-based implementation which is a sub-optimal solution.

**Comment by jakubklimek** [comment]
I do not understand... the CLEAR GRAPH query does not use the `query` parameter? Or what is the problem with the missing query mentioned in the exception? According to the [GraphDB SPARQL compliance](https://graphdb.ontotext.com/documentation/free/sparql-compliance.html#supported-parameters-for-requests-on-indirectly-referenced-named-graphs) page CLEAR GRAPH should be supported.
