### ISSUE TITLE
GraphStoreProtocol loader fails in some cases on NPE

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#934]
I am trying to load a single triple - maybe that is the cause?

```
2022-06-01 15:35:48,862 [asynchExecutor-1] ERROR c.l.e.e.e.ExecutionObserver - onExecuteComponentFailed : https://sk-nkod.opendata.cz/etl/resources/pipelines/1654089011176/15
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:51)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
at java.base/java.net.URLEncoder.encode(URLEncoder.java:224)
at com.linkedpipes.plugin.loader.graphstoreprotocol.GraphStoreProtocol.uploadGraphDb(GraphStoreProtocol.java:245)
at com.linkedpipes.plugin.loader.graphstoreprotocol.GraphStoreProtocol.executeEntry(GraphStoreProtocol.java:141)
at com.linkedpipes.plugin.loader.graphstoreprotocol.GraphStoreProtocol.execute(GraphStoreProtocol.java:68)
at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
at com.linkedpipes.etl.executor.api.v1.component.SequentialWrap.execute(SequentialWrap.java:49)
... 2 common frames omitted
```

**Comment by skodapetr** [comment]
Do you have an execution? This is caused by missing target graph, it should not be related to number of triples.

**Comment by jakubklimek** [comment]
This was caused by the tasks being connected to Configuration instead of Tasks. But after the update, at leas the error is descriptive.
