### ISSUE TITLE
JS errors when developing pipeline

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#94]
This one seems to be caused by dropping an edge onto an action icon (run to, invalidate, ...). This can be done by clicking target component (showing icons) and then dragging edge from another component and dropping it on an icon.
```
joint.js:995 Error: Invalid value for <path> attribute d="M NaN NaN NaN NaN"setAttribute @ joint.js:995
angular.js:12314 TypeError: Failed to execute 'setRotate' on 'SVGTransform': The provided float value is non-finite.
    at TypeError (native)
    at Object.VElement.translateAndAutoOrient (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:1544:32)
    at joint.dia.LinkView.joint.dia.CellView.extend._translateAndAutoOrientArrows (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:7422:25)
    at joint.dia.LinkView.joint.dia.CellView.extend.updateConnection (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:7030:14)
    at joint.dia.LinkView.joint.dia.CellView.extend.update (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:6980:14)
    at r [as update] (http://localhost:8080/app/components/pipelines/canvas/libraries/lodash/3.10.1/lodash.min.js:26:128)
    at joint.dia.LinkView.joint.dia.CellView.extend.render (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:6812:14)
    at joint.dia.Paper.joint.mvc.View.extend.renderView (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:8659:14)
    at joint.dia.Paper.joint.mvc.View.extend.onCellAdded (http://localhost:8080/app/components/pipelines/canvas/libraries/jointjs/0.9.7/joint.js:8637:18)
    at triggerEvents (http://localhost:8080/app/components/pipelines/canvas/libraries/backbone/1.2.3/backbone.js:370:57)
    at triggerApi (http://localhost:8080/app/components/pipelines/canvas/libraries/backbone/1.2.3/backbone.js:355:19)(anonymous function) @ angular.js:12314
2joint.js:995 Error: Invalid value for <path> attribute d="M NaN NaN NaN NaN"setAttribute @ joint.js:995
joint.js:1544 Uncaught TypeError: Failed to execute 'setRotate' on 'SVGTransform': The provided float value is non-finite.
```

**Comment by jakubklimek** [comment]
```
:8080/libraries/angularjs/1.4.1/angular-animate.js:734 Uncaught TypeError: Cannot read property '$$ngAnimateParentKey' of null
```

**Comment by jakubklimek** [comment]
Uncaught ReferenceError: onConnectionChange is not defined
