### ISSUE TITLE
JSON-LD Titanium framing does not work

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#954]
See [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1671630371169-0001&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1671630373973-1999-3072d025-bee4-4e92-ab03-ac307f67d84b).

The error is `Cannot invoke "String.length()" because "s" is null`:
```
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:42)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:39)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:38)
... 1 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
at java.base/java.io.StringReader.<init>(StringReader.java:51)
at com.linkedpipes.plugin.transformer.jsonldformattitanium.TitaniumOperator.documentFromString(TitaniumOperator.java:58)
at com.linkedpipes.plugin.transformer.jsonldformattitanium.TitaniumOperator.frameToJson(TitaniumOperator.java:108)
at com.linkedpipes.plugin.transformer.jsonldformattitanium.TitaniumOperator.frame(TitaniumOperator.java:101)
at com.linkedpipes.plugin.transformer.jsonldformattitanium.JsonLdFormatTitanium.transformFile(JsonLdFormatTitanium.java:79)
at com.linkedpipes.plugin.transformer.jsonldformattitanium.JsonLdFormatTitanium.execute(JsonLdFormatTitanium.java:43)
at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:37)
... 2 common frames omitted
```

**Comment by skodapetr** [comment]
This is problem with the configuration dialog, where the part with the frame was not visible and thus could not be provided. As the transformation is frame based the frame must be provided.
