### ISSUE TITLE
httpRequest fails on MIME type may not be null

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#965]
Tested with cdb415f271ad25737cba792080ddd965d1c2b063 
```
2023-05-23 08:16:03,864 [pool-367-thread-1] ERROR c.l.e.e.a.v.r.DefaultReportWriter - Task 'https://data.gov.cz/zdroj/datové-schránky/hkrkpwn' failed in 1 ms
java.lang.IllegalArgumentException: MIME type may not be null
	at org.apache.http.util.Args.notBlank(Args.java:71)
	at org.apache.http.entity.ContentType.create(ContentType.java:228)
	at org.apache.http.entity.ContentType.create(ContentType.java:241)
	at com.linkedpipes.plugin.http.apache.RequestExecutor.addPostBody(RequestExecutor.java:144)
	at com.linkedpipes.plugin.http.apache.RequestExecutor.createHttpWithBody(RequestExecutor.java:133)
	at com.linkedpipes.plugin.http.apache.RequestExecutor.createHttpMethod(RequestExecutor.java:83)
	at com.linkedpipes.plugin.http.apache.RequestExecutor.execute(RequestExecutor.java:47)
	at com.linkedpipes.plugin.http.request.main.TaskExecutor.accept(TaskExecutor.java:58)
	at com.linkedpipes.plugin.http.request.main.TaskExecutor.accept(TaskExecutor.java:20)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskConsumerWrap.executeTask(TaskConsumerWrap.java:77)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskConsumerWrap.executeTasks(TaskConsumerWrap.java:70)
	at com.linkedpipes.etl.executor.api.v1.component.task.TaskConsumerWrap.run(TaskConsumerWrap.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jakubklimek** [comment]
Fixed in 525e6bb02143189eb2d25e5a3c8efbc70498048e
