### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#97]
During pipeline save, I got this error from frontend:
```
Error: request entity too large
    at readStream (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\body-parser\node_modules\raw-body\index.js:196:17)
    at getRawBody (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\body-parser\node_modules\raw-body\index.js:106:12)
    at read (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\body-parser\lib\read.js:68:3)
    at jsonParser (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\body-parser\lib\types\json.js:121:5)
    at Layer.handle [as handle_request] (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (C:\Users\Kuba\Documents\GitHub\etl\deploy\frontend\node_modules\body-parser\lib\types\urlencoded.js:95:37)
```

**Comment by skodape** [comment]
Temporary solved by a12ec398ad1cc13e34a4296c9b79ae2c5dd00c1f. In future the pipeline should be processed by other component.
