### ISSUE TITLE
Wrong log message in Files to local

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#973]
<img width="308" alt="image" src="https://github.com/linkedpipes/etl/assets/718827/3c392d14-f89d-4058-9d66-311f1a6d52db">

In the log `AccessDeniedException`:
```
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:43)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:39)
at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:39)
... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't copy files.
at com.linkedpipes.plugin.loader.local.LoaderLocal.execute(LoaderLocal.java:68)
at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:37)
... 2 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /data/upload/nkd/katalog.ttl
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246)
at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
at java.base/java.nio.file.Files.copy(Files.java:1305)
at com.linkedpipes.plugin.loader.local.LoaderLocal.execute(LoaderLocal.java:64)
... 4 common frames omitted
```

**Comment by skodapetr** [comment]
The stack trace for file in a non existing directory is
```
com.linkedpipes.etl.executor.ExecutorException: PipelineComponent execution failed.
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:43)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Execution failed.
	at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:39)
	at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:39)
	... 1 common frames omitted
Caused by: com.linkedpipes.etl.executor.api.v1.LpException: Can't copy files.
	at com.linkedpipes.plugin.loader.local.LoaderLocal.execute(LoaderLocal.java:68)
	at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
	at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:37)
	... 2 common frames omitted
Caused by: java.nio.file.NoSuchFileException: /data/upload/nkd/test/katalog.ttl
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at com.linkedpipes.plugin.loader.local.LoaderLocal.execute(LoaderLocal.java:64)
	... 4 common frames omitted
```
where there is no AccessDeniedException exception. AccessDeniedException is for only a file in existing directory.

Yet we can check for permissions to better explain situation.
