### ISSUE TITLE
l-filesToScp cannot create directory in Bitvise SSHServer

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#99]
When creating directory in Bitvise SSHServer, an exception is thrown. Making the directory through putty works.

```
[Files to SCP] INFO  c.l.e.e.a.v.e.LocalizedException - Error: scp: /cygdrive/c/upload: Not a directory.

[Files to SCP] ERROR c.l.e.e.a.v.e.LocalizedException - LocalizedException
[Files to SCP] INFO  c.l.e.e.a.v.e.LocalizedException - Component failed!
com.linkedpipes.etl.dpu.api.DataProcessingUnit$ExecutionFailed: Error: {}
        at com.linkedpipes.plugin.loader.scp.LoaderScp.resonseCheck(LoaderScp.java:240) ~[na:na]
        at com.linkedpipes.plugin.loader.scp.LoaderScp.execute(LoaderScp.java:86) ~[na:na]
        at com.linkedpipes.etl.dpu.component.SequentialComponent.execute(SequentialComponent.java:263) ~[na:na]
        at com.linkedpipes.executor.execution.contoller.ComponentExecutor.run(ComponentExecutor.java:130) [executor.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
```

**Comment by jakubklimek** [comment]
@skarampatakis Is this still an issue with components which store files to a local file system directly?

**Comment by skarampatakis** [comment]
No, or at least I haven't noticed such behaviour.
Στις 19 Μαΐ 2016 4:12 μ.μ., ο χρήστης "Jakub Klímek" <
notifications@github.com> έγραψε:
